/**
 * Every active programme name in both sports, as the database holds them.
 *
 * Captured rather than invented, because the property under test is that the
 * hook alters nothing — and a hand-written list would only contain the
 * characters somebody thought to include. This one carries the apostrophes,
 * ampersands, parentheses and the single en-dash that are actually out there.
 */
export const PROGRAMME_NAMES = [
 "Adams State",
 "Adelphi",
 "Adrian",
 "Air Force",
 "Akron",
 "Alabama Huntsville",
 "Albany",
 "Albertus Magnus",
 "Albion",
 "Albright",
 "Alfred State",
 "Alfred University",
 "Allan Hancock",
 "Allegany",
 "Allegheny",
 "Allen County Community",
 "Alma",
 "Alvernia",
 "American",
 "American International",
 "American River",
 "Amherst",
 "Ancilla",
 "Anderson (IN)",
 "Anderson (SC)",
 "Anna Maria",
 "Anne Arundel",
 "Aquinas",
 "Arcadia",
 "Arizona Christian",
 "Arizona Western",
 "Army West Point",
 "Asbury",
 "Ashland",
 "Assumption",
 "Atlantic Cape",
 "Auburn Montgomery",
 "Augsburg",
 "Augustana (IL)",
 "Aurora",
 "Austin College",
 "Ave Maria University",
 "Averett",
 "Avila",
 "Babson",
 "Baker",
 "Baldwin Wallace",
 "Barclay",
 "Bard",
 "Barry",
 "Barton",
 "Barton County",
 "Bates",
 "Belhaven",
 "Bellarmine",
 "Bellevue University",
 "Belmont",
 "Belmont Abbey",
 "Beloit",
 "Benedictine (IL)",
 "Benedictine (KS)",
 "Benedictine University at Mesa",
 "Bentley",
 "Berea",
 "Berry",
 "Bethany (KS)",
 "Bethany (WV)",
 "Bethany Lutheran",
 "Bethel (IN)",
 "Bethel (MN)",
 "Bethel (TN)",
 "Bethel College (Kansas)",
 "Bethesda",
 "Binghamton",
 "Biola",
 "Blackburn",
 "Blinn",
 "Blue Mountain",
 "Blue Mountain Christian University",
 "Bluefield University",
 "Bluffton",
 "Bob Jones",
 "Bossier Parish",
 "Boston College",
 "Boston University",
 "Bowdoin",
 "Bowling Green",
 "Bradley",
 "Brandeis",
 "Brescia University",
 "Brevard",
 "Brewton-Parker Christian University",
 "Briar Cliff University",
 "Bridgeport",
 "Bridgewater (VA)",
 "Bridgewater State",
 "Brookdale",
 "Broward",
 "Brown",
 "Bryan",
 "Bryant",
 "Bryant & Stratton College (Albany)",
 "Bryn Athyn",
 "Bucknell",
 "Buena Vista",
 "Buffalo-Erie",
 "Bushnell University",
 "Butler",
 "Butler County",
 "CSUN",
 "Cairn",
 "Cal Lutheran",
 "Cal Poly",
 "Cal Poly Humboldt",
 "Cal Poly Pomona",
 "Cal State Bakersfield",
 "Cal State Dominguez Hills",
 "Cal State East Bay",
 "Cal State Fullerton",
 "Cal State LA",
 "Cal State Monterey Bay",
 "Cal State San Bernardino",
 "Cal State San Marcos",
 "Cal State Stanislaus",
 "Caldwell",
 "California",
 "California Baptist",
 "Caltech",
 "Calumet College",
 "Calumet College of St. Joseph",
 "Calvin",
 "Campbell",
 "Campbellsville University",
 "Canisius",
 "Cape Fear",
 "Capital",
 "Carl Sandburg",
 "Carleton",
 "Carlow",
 "Carnegie Mellon",
 "Carolina University",
 "Carroll (MT)",
 "Carroll (WI)",
 "Carson-Newman",
 "Carthage",
 "Cascadia",
 "Case Western Reserve",
 "Catawba",
 "Catawba Valley",
 "Catholic",
 "Cecil",
 "Cedarville",
 "Centenary (LA)",
 "Centenary (NJ)",
 "Central (IA)",
 "Central Alabama",
 "Central Arizona",
 "Central Arkansas",
 "Central Baptist College",
 "Central Christian",
 "Central Connecticut",
 "Central Georgia Tech",
 "Central Lakes",
 "Central Methodist",
 "Central Penn",
 "Centre",
 "Chaminade",
 "Chapman",
 "Charleston",
 "Charleston (WV)",
 "Charlotte",
 "Chatham",
 "Chesapeake",
 "Chestnut Hill",
 "Chicago State",
 "Chico State",
 "Chipola",
 "Chowan",
 "Christian Brothers",
 "Christopher Newport",
 "City Colleges Chicago-Harold Washington",
 "City Colleges Chicago-Olive Harvey",
 "City Colleges Chicago-Richard Daley",
 "City Colleges Chicago-Wilbur Wright",
 "Claremont-Mudd-Scripps",
 "Clark (MA)",
 "Clarke",
 "Clarkson",
 "Clayton State",
 "Cleary University",
 "Clemson",
 "Cleveland State",
 "Coastal Carolina",
 "Coe",
 "Coffeyville",
 "Coker",
 "Colby",
 "Colby-Sawyer",
 "Colgate",
 "College of DuPage",
 "College of Idaho",
 "College of Lake County",
 "College of Marin",
 "College of Southern Idaho",
 "College of Southern Nevada",
 "College of Wooster",
 "Collin College",
 "Colorado Christian",
 "Colorado College",
 "Colorado Mesa",
 "Colorado School of Mines",
 "Colorado State-Pueblo",
 "Columbia",
 "Columbia (MO)",
 "Columbia College (SC)",
 "Columbia International University",
 "Commonwealth University-Bloomsburg",
 "Commonwealth University-Lock Haven",
 "Concord",
 "Concordia (MI)",
 "Concordia (MN)",
 "Concordia (NE)",
 "Concordia Chicago",
 "Concordia Irvine",
 "Concordia Texas",
 "Concordia Wisconsin",
 "Connecticut College",
 "Contra Costa",
 "Converse",
 "Copiah-Lincoln",
 "Corban University",
 "Cornell",
 "Cornell College",
 "Cornerstone",
 "Covenant",
 "Cowley County",
 "Creighton",
 "Crowder",
 "Crown (MN)",
 "Culver-Stockton College",
 "Cumberland University",
 "Cumberlands",
 "Curry",
 "D'Youville",
 "Daemen",
 "Dakota Wesleyan",
 "Dallas Baptist",
 "Dallas Christian",
 "Dalton State College",
 "Danville Area",
 "Dartmouth",
 "Davenport",
 "Davidson",
 "Davis & Elkins",
 "Dayton",
 "Daytona State",
 "DePaul",
 "DePauw",
 "DeSales",
 "Dean College",
 "Defiance College",
 "Delaware",
 "Delaware Valley",
 "Delta College (MI)",
 "Delta State",
 "Denison",
 "Denver",
 "Des Moines Area",
 "Detroit Mercy",
 "Diablo Valley",
 "Dickinson",
 "District of Columbia",
 "Doane",
 "Dodge City",
 "Dominican (CA)",
 "Dominican (IL)",
 "Dominican College (NY)",
 "Dordt",
 "Drake",
 "Drew",
 "Drexel",
 "Drury",
 "Duke",
 "Duquesne",
 "ETSU",
 "Earlham",
 "East Central (OK)",
 "East Mississippi",
 "East Stroudsburg",
 "East Texas Baptist",
 "Eastern (PA)",
 "Eastern Arizona",
 "Eastern Connecticut",
 "Eastern Florida State",
 "Eastern Illinois",
 "Eastern Mennonite",
 "Eastern New Mexico",
 "Eastern Oregon",
 "Eastern Wyoming",
 "Eckerd",
 "Edgewood",
 "El Camino",
 "Elizabethtown",
 "Ellsworth",
 "Elmhurst",
 "Elmira",
 "Elms",
 "Elon",
 "Embry-Riddle",
 "Embry-Riddle Aeronautical University Prescott",
 "Emerson",
 "Emmanuel (GA)",
 "Emmanuel (MA)",
 "Emory",
 "Emory & Henry",
 "Endicott",
 "Erskine",
 "Essex County",
 "Eureka",
 "Evangel",
 "Evansville",
 "Everett",
 "FDU-Florham",
 "FGCU",
 "FIU",
 "Fairfield",
 "Fairleigh Dickinson",
 "Faulkner University",
 "Felician",
 "Ferrum",
 "Findlay",
 "Finger Lakes Community",
 "Fisher College",
 "Fitchburg State",
 "Five Towns College",
 "Flagler",
 "Florida Atlantic",
 "Florida College",
 "Florida Memorial",
 "Florida National University",
 "Florida Southern",
 "Florida State College Jacksonville",
 "Florida Tech",
 "Fordham",
 "Fort Hays State",
 "Fort Lewis",
 "Fort Scott Community",
 "Framingham State",
 "Francis Marion",
 "Franciscan (OH)",
 "Franklin",
 "Franklin & Marshall",
 "Franklin Pierce",
 "Frederick",
 "Fredonia State",
 "Freed-Hardeman",
 "Fresno Pacific",
 "Friends",
 "Front Range",
 "Frostburg State",
 "Furman",
 "Gadsden State",
 "Gallaudet",
 "Gannon",
 "Garden City Community",
 "Gardner-Webb",
 "Garrett",
 "Genesee Community",
 "Geneva",
 "George C. Wallace",
 "George Fox",
 "George Mason",
 "George Washington",
 "Georgetown",
 "Georgetown (KY)",
 "Georgia Gwinnett College",
 "Georgia Highlands",
 "Georgia Military",
 "Georgia Northwestern",
 "Georgia Piedmont",
 "Georgia Southern",
 "Georgia Southwestern",
 "Georgia State",
 "Georgian Court",
 "Gettysburg",
 "Gloucester County",
 "Goldey-Beacom",
 "Gonzaga",
 "Gordon",
 "Goshen",
 "Goucher",
 "Governors State University",
 "Grace",
 "Grace Christian",
 "Graceland University",
 "Grand Canyon",
 "Grand Rapids Community",
 "Grand View",
 "Green Bay",
 "Greensboro",
 "Greenville",
 "Grinnell",
 "Grove City",
 "Guilford",
 "Gustavus Adolphus",
 "Gwynedd Mercy",
 "Hagerstown",
 "Hamilton",
 "Hamline",
 "Hampden-Sydney",
 "Hannibal-LaGrange",
 "Hanover",
 "Hardin-Simmons",
 "Harding",
 "Harford County",
 "Harper",
 "Harris-Stowe State University",
 "Hartford",
 "Hartwick",
 "Harvard",
 "Hastings",
 "Haverford",
 "Hawaii Hilo",
 "Hawaii Pacific",
 "Hawkeye",
 "Heidelberg",
 "Hendrix",
 "Hesston College",
 "High Point",
 "Highland",
 "Hilbert",
 "Hillsborough",
 "Hiram",
 "Hobart & William Smith",
 "Hocking",
 "Hofstra",
 "Holmes",
 "Holy Cross",
 "Holy Cross College",
 "Holy Family",
 "Holyoke",
 "Hood",
 "Hope",
 "Hope International University",
 "Houghton",
 "Houston Christian",
 "Howard",
 "Howard Community",
 "Howard Payne",
 "Hudson Valley",
 "Huntingdon",
 "Huntington",
 "Husson",
 "Huston-Tillotson University",
 "IU Indy",
 "Illinois College",
 "Illinois Springfield",
 "Illinois Tech",
 "Illinois Wesleyan",
 "Immaculata",
 "Indian Hills",
 "Indiana",
 "Indiana Institute of Technology",
 "Indiana University Columbus",
 "Indiana University East",
 "Indiana University Northwest",
 "Indiana Wesleyan",
 "Indianapolis",
 "Iona",
 "Iowa Central",
 "Iowa Lakes",
 "Iowa Wesleyan",
 "Iowa Western",
 "Ithaca",
 "J. Sargeant Reynolds",
 "Jackson College",
 "Jacksonville",
 "James Madison",
 "Jamestown",
 "Jefferson (NY)",
 "Jefferson Davis",
 "Jessup",
 "John Brown",
 "John Carroll",
 "Johns Hopkins",
 "Johnson & Wales (Charlotte)",
 "Johnson & Wales (Providence)",
 "Johnson County Community",
 "Johnson University",
 "Judson University",
 "Juniata",
 "Kalamazoo",
 "Kalamazoo Valley",
 "Kankakee Community",
 "Kansas City",
 "Kansas Wesleyan",
 "Kean",
 "Keene State",
 "Keiser University",
 "Kellogg Community",
 "Kentucky",
 "Kentucky Christian",
 "Kentucky Wesleyan",
 "Kenyon",
 "Keuka",
 "Keystone",
 "Kilgore",
 "King (TN)",
 "King's (PA)",
 "Kirkwood",
 "Knox",
 "LIU",
 "LSU Alexandria",
 "LSU Shreveport",
 "La Roche",
 "La Salle",
 "La Sierra University",
 "LaGrange",
 "Labette",
 "Lafayette",
 "Lake Erie",
 "Lake Forest",
 "Lake Land",
 "Lakeland",
 "Lamar Institute",
 "Lancaster Bible",
 "Lander",
 "Laramie County",
 "Lasell",
 "Lawrence",
 "Lawrence Technological University",
 "Le Moyne",
 "LeTourneau",
 "Lebanon Valley",
 "Lee (TN)",
 "Lees-McRae",
 "Lehigh",
 "Lenoir-Rhyne",
 "Lesley",
 "Lewis",
 "Lewis & Clark",
 "Lewis & Clark (ID)",
 "Liberty",
 "Life (GA)",
 "Lincoln (MO)",
 "Lincoln Land",
 "Lincoln Memorial",
 "Lincoln Trail",
 "Lindenwood",
 "Lindsey Wilson",
 "Linfield",
 "Lipscomb",
 "Lone Star",
 "Longwood",
 "Loras",
 "Lord Fairfax",
 "Louisiana Christian University",
 "Louisiana Delta",
 "Louisville",
 "Lower Columbia",
 "Loyola Chicago",
 "Loyola Maryland",
 "Loyola Marymount",
 "Lubbock Christian",
 "Lurleen B. Wallace",
 "Luther",
 "Lycoming",
 "Lynn",
 "Lyon College",
 "MIT",
 "Macalester",
 "Madonna University",
 "Maine Maritime",
 "Malone",
 "Manchester",
 "Manhattan",
 "Manhattanville",
 "Marian (WI)",
 "Marian University (IN)",
 "Marietta",
 "Marist",
 "Marquette",
 "Mars Hill",
 "Marshall",
 "Martin Luther",
 "Mary Baldwin",
 "Maryland",
 "Marymount (VA)",
 "Maryville (MO)",
 "Maryville (TN)",
 "Marywood",
 "Massachusetts College of Liberal Arts",
 "Massachusetts Maritime",
 "McDaniel",
 "McKendree",
 "McLennan",
 "McMurry",
 "McPherson College",
 "Memphis",
 "Menlo",
 "Merced",
 "Mercer",
 "Mercy",
 "Mercyhurst",
 "Meridian",
 "Merrimack",
 "Mesa Community",
 "Messiah",
 "Methodist",
 "Metro State Denver",
 "Michigan",
 "Michigan State",
 "Mid-America Christian University",
 "MidAmerica Nazarene",
 "Middle Georgia State",
 "Middlebury",
 "Middlesex County",
 "Midland",
 "Midway",
 "Midwestern State",
 "Millersville",
 "Milligan University",
 "Millikin",
 "Millsaps",
 "Milwaukee",
 "Mineral Area",
 "Mission University",
 "Mississippi College",
 "Mississippi Delta",
 "Mississippi Gulf Coast",
 "Missouri Baptist",
 "Missouri S&T",
 "Missouri State",
 "Missouri State-West Plains",
 "Missouri Valley College",
 "Moberly Area",
 "Molloy",
 "Monmouth",
 "Monmouth (IL)",
 "Monroe (NY)",
 "Monroe Community",
 "Montclair State",
 "Montevallo",
 "Montgomery",
 "Montreat College",
 "Moravian",
 "Morningside",
 "Motlow State",
 "Mount Marty University",
 "Mount Mercy",
 "Mount Olive",
 "Mount San Antonio",
 "Mount St. Joseph",
 "Mount St. Mary's",
 "Mount Union",
 "Mount Vernon Nazarene",
 "Muhlenberg",
 "Muskingum",
 "NC State",
 "NJIT",
 "Nassau Community",
 "Navy",
 "Nazareth",
 "Nebraska Central",
 "Nelson University",
 "New College of Florida",
 "New England College",
 "New Hampshire",
 "New Haven",
 "New Jersey City",
 "New Mexico Junior",
 "New York University",
 "Newberry",
 "Newman",
 "Niagara",
 "Niagara County",
 "Nichols",
 "North American University",
 "North Arkansas",
 "North Carolina",
 "North Carolina Wesleyan",
 "North Central (IL)",
 "North Central Missouri",
 "North Florida",
 "North Georgia",
 "North Park",
 "Northeast Mississippi",
 "Northeast Oklahoma A&M",
 "Northeast Texas",
 "Northeastern",
 "Northeastern State",
 "Northern Essex",
 "Northern Idaho",
 "Northern Illinois",
 "Northern Kentucky",
 "Northern Michigan",
 "Northland Pioneer",
 "Northwest College",
 "Northwest Mississippi",
 "Northwest Nazarene",
 "Northwest Shoals",
 "Northwest University",
 "Northwestern",
 "Northwestern (IA)",
 "Northwestern (MN)",
 "Northwood",
 "Notre Dame",
 "Nova Southeastern",
 "Oakland",
 "Oakland City University",
 "Oakwood University",
 "Oberlin",
 "Odessa",
 "Oglethorpe",
 "Ohio Dominican",
 "Ohio Northern",
 "Ohio State",
 "Ohio Wesleyan",
 "Oklahoma Christian",
 "Oklahoma City Community",
 "Oklahoma Panhandle State University",
 "Oklahoma Wesleyan University",
 "Old Dominion",
 "Olivet",
 "Olivet Nazarene",
 "Omaha",
 "Onondaga Community",
 "Oral Roberts",
 "Orange Coast",
 "Oregon Institute of Technology",
 "Oregon State",
 "Otero College",
 "Ottawa",
 "Ottawa University Arizona",
 "Otterbein",
 "Ouachita Baptist",
 "Our Lady of the Lake University",
 "Owens",
 "Ozarka",
 "Ozarks (AR)",
 "Ozarks (MO)",
 "Pace",
 "Pacific",
 "Pacific Lutheran",
 "Pacific Union College",
 "Palm Beach Atlantic",
 "Panola",
 "Paradise Valley",
 "Park",
 "Park University Gilbert",
 "Parkland",
 "Passaic County",
 "Paul D. Camp",
 "Paul Quinn College",
 "Pearl River",
 "Pellissippi State",
 "Penn",
 "Penn State",
 "Penn State Beaver",
 "Penn State Behrend",
 "Penn State Greater Allegheny",
 "Penn State Harrisburg",
 "Penn State Hazleton",
 "Penn State Lehigh Valley",
 "Penn State Mont Alto",
 "Penn State New Kensington",
 "Penn State Schuylkill",
 "Penn State Scranton",
 "Penn State York",
 "PennWest California",
 "PennWest Johnstown",
 "Pensacola State",
 "Piedmont Virginia",
 "Pikeville",
 "Pima",
 "Pittsburgh",
 "Plattsburgh State",
 "Plymouth State",
 "Point (GA)",
 "Point Loma Nazarene",
 "Point Park",
 "Polk State",
 "Pomona-Pitzer",
 "Portland",
 "Post",
 "Prairie State",
 "Pratt Community",
 "Presbyterian",
 "Princeton",
 "Providence",
 "Providence (MT)",
 "Puget Sound",
 "Purdue Fort Wayne",
 "Purdue Northwest",
 "Queens (CUNY)",
 "Queens (NC)",
 "Queensborough",
 "Quincy",
 "Quinnipiac",
 "Radford",
 "Randolph-Macon",
 "Ranger",
 "Reading Area",
 "Regis (CO)",
 "Reinhardt University",
 "Rend Lake",
 "Rensselaer",
 "Rhode Island",
 "Rhode Island College",
 "Rhodes",
 "Richland",
 "Rider",
 "Rio Grande (University of)",
 "Ripon",
 "Riverside",
 "Roane State",
 "Roanoke",
 "Robert Morris",
 "Roberts Wesleyan",
 "Rochester",
 "Rochester Christian University",
 "Rochester Institute of Technology",
 "Rock Valley",
 "Rockhurst",
 "Rockland Community",
 "Rocky Mountain",
 "Roger Williams",
 "Rogers State",
 "Rollins",
 "Roosevelt",
 "Rose State",
 "Rose-Hulman",
 "Rowan",
 "Rutgers",
 "Rutgers-Camden",
 "Rutgers-Newark",
 "SCAD",
 "SIUE",
 "SMU",
 "SUNY Cortland",
 "SUNY Geneseo",
 "SUNY New Paltz",
 "SUNY Old Westbury",
 "SUNY Oneonta",
 "SUNY Oswego",
 "SUNY Potsdam",
 "Sacramento State",
 "Sacred Heart",
 "Saginaw Valley State",
 "Saint Ambrose",
 "Saint Anselm",
 "Saint Francis (IL)",
 "Saint Francis (PA)",
 "Saint John Fisher",
 "Saint Joseph's",
 "Saint Joseph's (ME)",
 "Saint Lawrence",
 "Saint Leo",
 "Saint Louis",
 "Saint Martin's",
 "Saint Mary (KS)",
 "Saint Mary's",
 "Saint Mary's (MN)",
 "Saint Mary-of-the-Woods College",
 "Saint Michael's",
 "Saint Olaf",
 "Saint Peter's",
 "Saint Thomas (FL)",
 "Saint Vincent",
 "Saint Xavier University",
 "Salem",
 "Salisbury",
 "Salt Lake Community",
 "Salve Regina",
 "San Bernardino Valley",
 "San Diego",
 "San Diego Mesa",
 "San Diego Miramar",
 "San Diego State",
 "San Francisco",
 "San Francisco State",
 "San Joaquin Delta",
 "San Jose State",
 "Sandhills",
 "Santa Ana",
 "Santa Barbara City",
 "Santa Clara",
 "Santa Monica",
 "Santa Rosa Junior",
 "Savannah College of Art and Design",
 "Science & Arts (OK)",
 "Scottsdale",
 "Scranton",
 "Seattle",
 "Seattle Pacific",
 "Seton Hall",
 "Seton Hill",
 "Seward County",
 "Shaw",
 "Shawnee Community",
 "Shawnee State",
 "Shawnee State University",
 "Shenandoah",
 "Shepherd",
 "Shippensburg",
 "Shorter",
 "Siena",
 "Siena Heights",
 "Sierra",
 "Simon Fraser",
 "Simpson (IA)",
 "Simpson University",
 "Sinclair",
 "Skagit Valley",
 "Skidmore",
 "Slippery Rock",
 "Snow",
 "Soka University of America",
 "Somerset",
 "South Carolina",
 "South Carolina Aiken",
 "South Dakota Mines",
 "South Florida",
 "South Mountain Community",
 "South Plains",
 "South Puget Sound",
 "Southeastern Community (IA)",
 "Southeastern University",
 "Southern Connecticut State",
 "Southern Indiana",
 "Southern Maine",
 "Southern Nazarene",
 "Southern New Hampshire",
 "Southern Oregon",
 "Southern Virginia",
 "Southern Wesleyan",
 "Southwest Baptist",
 "Southwest Minnesota State",
 "Southwestern (CA)",
 "Southwestern (KS)",
 "Southwestern (TX)",
 "Southwestern Christian University",
 "Southwestern Illinois",
 "Spartanburg Methodist",
 "Spartanburg Methodist College",
 "Spring Arbor",
 "Spring Hill",
 "Springfield",
 "St. Bonaventure",
 "St. Charles Community",
 "St. Cloud State",
 "St. John's",
 "St. Joseph's (NY)",
 "St. Louis Community-Florissant Valley",
 "St. Louis Community-Forest Park",
 "St. Louis Community-Meramec",
 "St. Mary's (TX)",
 "St. Mary's College of Maryland",
 "St. Norbert",
 "St. Scholastica",
 "St. Thomas",
 "St. Thomas Aquinas",
 "Stanford",
 "Staten Island",
 "Sterling",
 "Stetson",
 "Stevens Tech",
 "Stevenson",
 "Stockton",
 "Stonehill",
 "Stony Brook",
 "Suffolk",
 "Suffolk County",
 "Sul Ross State",
 "Sullivan County",
 "Surry",
 "Susquehanna",
 "Swarthmore",
 "Syracuse",
 "Tabor",
 "Talladega College",
 "Tallahassee",
 "Tampa",
 "Taylor",
 "Temple",
 "Tennessee Wesleyan University",
 "Terra State",
 "Texas A&M International",
 "Texas A&M University-San Antonio",
 "Texas A&M University-Texarkana",
 "Texas A&M University-Victoria",
 "Texas College",
 "Texas Wesleyan University",
 "The Evergreen State College",
 "The Master's University",
 "Thomas Jefferson",
 "Thomas More",
 "Thomas University",
 "Three Rivers",
 "Tidewater",
 "Tiffin",
 "Tompkins Cortland",
 "Tougaloo College",
 "Trevecca Nazarene",
 "Trine",
 "Trinity (CT)",
 "Trinity (TX)",
 "Trinity Christian",
 "Trinity Valley",
 "Truett McConnell University",
 "Truman State",
 "Tufts",
 "Tulsa",
 "Tulsa Community",
 "Tusculum",
 "Tyler Junior",
 "UAB",
 "UC Davis",
 "UC Irvine",
 "UC Merced",
 "UC Riverside",
 "UC San Diego",
 "UC Santa Barbara",
 "UCCS",
 "UCF",
 "UCLA",
 "UConn",
 "UIC",
 "UIW",
 "UMBC",
 "UMSL",
 "UMass",
 "UMass Lowell",
 "UNC Asheville",
 "UNC Greensboro",
 "UNCW",
 "UNLV",
 "USC Upstate",
 "UT Dallas",
 "UT Tyler",
 "UTRGV",
 "Union (KY)",
 "Union (NY)",
 "Union (TN)",
 "Union County",
 "University of Chicago",
 "University of Health Sciences and Pharmacy in St. Louis",
 "University of Michigan-Dearborn",
 "University of Mobile",
 "University of New England",
 "University of Northwestern Ohio",
 "University of Saint Francis (IN)",
 "University of Tennessee Southern",
 "University of the Southwest (New Mexico)",
 "Upper Iowa",
 "Ursinus",
 "Utah Tech",
 "Utah Valley",
 "Utica",
 "VCU",
 "VMI",
 "Vanguard",
 "Ventura",
 "Vermont",
 "Vernon",
 "Victor Valley",
 "Villanova",
 "Vincennes",
 "Virginia",
 "Virginia Highlands",
 "Virginia State",
 "Virginia Tech",
 "Virginia Wesleyan",
 "Virginia Western",
 "Volunteer State",
 "Wake Forest",
 "Wake Technical",
 "Waldorf",
 "Walla Walla University",
 "Wallace State",
 "Walsh",
 "Walters State",
 "Warner",
 "Warner Pacific University",
 "Wartburg",
 "Washington",
 "Washington & Jefferson",
 "Washington & Lee",
 "Washington (MO)",
 "Washington Adventist University",
 "Washington College (MD)",
 "Wayland Baptist",
 "Waynesburg",
 "Weatherford",
 "Webber International",
 "Webster",
 "Wentworth",
 "Wesleyan (CT)",
 "West Alabama",
 "West Chester",
 "West Florida",
 "West Liberty",
 "West Texas A&M",
 "West Virginia",
 "West Virginia University Institute of Technology",
 "West Virginia Wesleyan",
 "Westcliff University",
 "Western Connecticut",
 "Western Illinois",
 "Western Michigan",
 "Western Nebraska",
 "Western New England",
 "Western Oregon",
 "Western Washington",
 "Western Wyoming",
 "Westfield State",
 "Westminster (MO)",
 "Westminster (PA)",
 "Westminster (UT)",
 "Westmont",
 "Westmoreland County",
 "Wharton County Junior",
 "Wheaton (IL)",
 "Wheaton (MA)",
 "Wheeling",
 "Whitman",
 "Whitworth",
 "Widener",
 "Wiley University",
 "Wilkes",
 "William & Mary",
 "William Carey University",
 "William Jewell",
 "William Penn",
 "William Rainey Harper",
 "William Woods",
 "Williams",
 "Williams Baptist University",
 "Wilmington (DE)",
 "Wilmington (OH)",
 "Wingate",
 "Winthrop",
 "Wisconsin",
 "Wisconsin-Eau Claire",
 "Wisconsin-La Crosse",
 "Wisconsin-Oshkosh",
 "Wisconsin-Parkside",
 "Wisconsin-Platteville",
 "Wisconsin-River Falls",
 "Wisconsin-Stevens Point",
 "Wisconsin-Stout",
 "Wisconsin-Superior",
 "Wisconsin-Whitewater",
 "Wittenberg",
 "Wofford",
 "Worcester Polytechnic",
 "Worcester State",
 "Wright State",
 "Xavier",
 "Xavier (LA)",
 "Yale",
 "Yeshiva",
 "York (PA)",
 "York County",
 "York University (Nebraska)",
 "Young Harris",
 "Abilene Christian",
 "Abraham Baldwin Agricultural College",
 "Adams State",
 "Adelphi",
 "Adrian College",
 "Agnes Scott College",
 "Air Force",
 "Akron",
 "Alabama",
 "Alabama A&M",
 "Alabama Huntsville",
 "Alabama State",
 "Albany",
 "Albertus Magnus",
 "Albion College",
 "Albright College",
 "Alcorn State",
 "Alfred University",
 "Allegheny College",
 "Allen",
 "Alma College",
 "Alvernia University",
 "Alverno College",
 "American",
 "American International",
 "Amherst College",
 "Anderson (SC)",
 "Anderson University (IN)",
 "Angelo State",
 "Anna Maria College",
 "Appalachian State",
 "Aquinas College (Michigan)",
 "Arcadia University",
 "Arizona",
 "Arizona Christian University",
 "Arizona State",
 "Arkansas",
 "Arkansas State",
 "Arkansas-Pine Bluff",
 "Army",
 "Asbury University",
 "Ashland",
 "Assumption",
 "Auburn",
 "Auburn Montgomery",
 "Augsburg University",
 "Augustana (SD)",
 "Augustana College",
 "Aurora University",
 "Austin College",
 "Austin Peay",
 "Ave Maria University",
 "Averett University",
 "Avila University",
 "Azusa Pacific University",
 "BYU",
 "Babson College",
 "Baker University",
 "Baldwin Wallace University",
 "Ball State",
 "Bard College",
 "Barry",
 "Barton",
 "Bates College",
 "Batten University",
 "Bay Path University",
 "Baylor",
 "Belhaven University",
 "Bellarmine",
 "Bellevue University",
 "Belmont",
 "Belmont Abbey",
 "Beloit College",
 "Bemidji State",
 "Benedictine College",
 "Benedictine University",
 "Benedictine University at Mesa",
 "Bentley",
 "Berea College",
 "Berry College",
 "Bethany College (Kansas)",
 "Bethany College (WV)",
 "Bethany Lutheran College",
 "Bethel College (Kansas)",
 "Bethel University (IN)",
 "Bethel University (MN)",
 "Bethel University (TN)",
 "Binghamton",
 "Biola",
 "Black Hills State",
 "Blackburn College",
 "Blue Mountain Christian University",
 "Bluefield State",
 "Bluefield University",
 "Bluffton University",
 "Boise State",
 "Boston College",
 "Boston University",
 "Bowdoin College",
 "Bowling Green",
 "Brandeis University",
 "Brenau University",
 "Brescia University",
 "Brevard College",
 "Brewton-Parker Christian University",
 "Briar Cliff University",
 "Bridgeport",
 "Bridgewater College",
 "Bridgewater State University",
 "Brown",
 "Bryan College",
 "Bryant",
 "Bryant & Stratton-Syracuse",
 "Bryn Athyn College of the New Church",
 "Bryn Mawr College",
 "Bucknell",
 "Buena Vista University",
 "Buffalo",
 "Bushnell University",
 "Butler",
 "CUNY Brooklyn College",
 "CUNY City College",
 "CUNY John Jay College of Criminal Justice",
 "CUNY Lehman College",
 "CUNY Medgar Evers College",
 "CUNY York College",
 "Cairn University",
 "Cal Lutheran",
 "Cal Poly",
 "Cal Poly Humboldt",
 "Cal Poly Pomona",
 "Cal State Bakersfield",
 "Cal State Dominguez Hills",
 "Cal State East Bay",
 "Cal State Fullerton",
 "Cal State Los Angeles",
 "Cal State Monterey Bay",
 "Cal State Northridge",
 "Cal State San Bernardino",
 "Cal State San Marcos",
 "Cal State Stanislaus",
 "Caldwell",
 "California",
 "California Baptist",
 "California Institute of Technology",
 "California Lutheran University",
 "Calumet College of St. Joseph",
 "Calvin University",
 "Campbell",
 "Campbellsville University",
 "Canisius",
 "Capital University",
 "Carleton College",
 "Carlow University",
 "Carnegie Mellon University",
 "Carolina University",
 "Carroll College",
 "Carroll University",
 "Carson-Newman",
 "Carthage College",
 "Case Western Reserve University",
 "Catawba",
 "Catholic University of America",
 "Cedar Crest College",
 "Cedarville",
 "Centenary College of Louisiana",
 "Centenary University",
 "Central Arkansas",
 "Central Baptist College",
 "Central Christian College of Kansas",
 "Central College",
 "Central Connecticut",
 "Central Methodist University",
 "Central Michigan",
 "Central Missouri",
 "Central Oklahoma",
 "Central Penn College",
 "Central Washington",
 "Centre College",
 "Chaminade",
 "Chapman University",
 "Charleston",
 "Charleston (WV)",
 "Charleston Southern",
 "Charlotte",
 "Chatham University",
 "Chattanooga",
 "Chestnut Hill",
 "Chicago State",
 "Chico State",
 "Chowan",
 "Christendom College",
 "Christian Brothers",
 "Christopher Newport University",
 "Cincinnati",
 "Claremont McKenna College",
 "Claremont-Mudd-Scripps",
 "Clark University",
 "Clarke University",
 "Clarkson University",
 "Clayton State",
 "Cleary University",
 "Clemson",
 "Cleveland State",
 "Coastal Carolina",
 "Coe College",
 "Coker",
 "Colby College",
 "Colby-Sawyer",
 "Colgate",
 "College of Idaho",
 "College of Mount Saint Vincent",
 "College of Saint Benedict",
 "College of Saint Mary",
 "Colorado",
 "Colorado Christian",
 "Colorado College",
 "Colorado Mesa",
 "Colorado School of Mines",
 "Colorado State",
 "Colorado State-Pueblo",
 "Columbia",
 "Columbia College (MO)",
 "Columbia College (SC)",
 "Columbia International University",
 "Columbus State",
 "Commonwealth University-Bloomsburg",
 "Commonwealth University-Lock Haven",
 "Commonwealth University-Mansfield",
 "Concord",
 "Concordia College-Moorhead",
 "Concordia Irvine",
 "Concordia University Nebraska",
 "Concordia University-Chicago",
 "Concordia University-Texas",
 "Concordia University-Wisconsin",
 "Concordia-St. Paul",
 "Connecticut College",
 "Converse",
 "Corban University",
 "Cornell",
 "Cornell College",
 "Cornerstone University",
 "Covenant College",
 "Creighton",
 "Crown College",
 "Culver-Stockton College",
 "Cumberland University",
 "Curry College",
 "D'Youville",
 "Daemen",
 "Dakota State University",
 "Dakota Wesleyan University",
 "Dallas Baptist",
 "Dalton State College",
 "Dartmouth",
 "Davenport",
 "Davidson",
 "Davis & Elkins",
 "Dayton",
 "DePaul",
 "DePauw University",
 "DeSales University",
 "Dean",
 "Defiance College",
 "Delaware",
 "Delaware State",
 "Delaware Valley University",
 "Delta State",
 "Denison University",
 "Denver",
 "Detroit Mercy",
 "Dickinson College",
 "Doane University",
 "Dominican (CA)",
 "Dominican (NY)",
 "Dominican University",
 "Dordt University",
 "Drake",
 "Drew University",
 "Drexel",
 "Drury",
 "Duke",
 "Duquesne",
 "Earlham College",
 "East Carolina",
 "East Central",
 "East Stroudsburg",
 "East Tennessee State",
 "East Texas A&M",
 "East Texas Baptist University",
 "Eastern Connecticut",
 "Eastern Illinois",
 "Eastern Kentucky",
 "Eastern Mennonite University",
 "Eastern Michigan",
 "Eastern New Mexico",
 "Eastern Oregon University",
 "Eastern University",
 "Eastern Washington",
 "Eckerd",
 "Edgewood College",
 "Edward Waters",
 "Elizabethtown College",
 "Elmhurst University",
 "Elmira College",
 "Elms",
 "Elon",
 "Embry-Riddle Aeronautical University Prescott",
 "Embry–Riddle Aeronautical",
 "Emerson College",
 "Emmanuel (GA)",
 "Emory & Henry",
 "Emory University",
 "Emporia State",
 "Endicott College",
 "Erskine",
 "Eureka College",
 "Evangel University",
 "Evansville",
 "FDU-Florham",
 "FIU",
 "Fairfield",
 "Fairleigh Dickinson",
 "Fairleigh Dickinson University-Florham",
 "Fairmont State",
 "Farmingdale State College",
 "Faulkner University",
 "Felician",
 "Ferris State",
 "Ferrum",
 "Findlay",
 "Fisher College",
 "Fitchburg State University",
 "Flagler",
 "Florida",
 "Florida Atlantic",
 "Florida College",
 "Florida Gulf Coast",
 "Florida Memorial University",
 "Florida National University",
 "Florida Southern",
 "Florida State",
 "Florida Tech",
 "Fordham",
 "Fort Hays State",
 "Fort Lewis",
 "Framingham State University",
 "Francis Marion",
 "Franciscan University of Steubenville",
 "Franklin & Marshall College",
 "Franklin College",
 "Franklin Pierce",
 "Freed-Hardeman University",
 "Fresno Pacific",
 "Fresno State",
 "Friends University",
 "Frostburg State",
 "Furman",
 "Gannon",
 "Gardner-Webb",
 "Geneva College",
 "George Fox University",
 "George Mason",
 "George Washington",
 "Georgetown",
 "Georgetown College",
 "Georgia",
 "Georgia College",
 "Georgia Gwinnett College",
 "Georgia Southern",
 "Georgia Southwestern",
 "Georgia State",
 "Georgian Court",
 "Gettysburg College",
 "Glenville State",
 "Goldey-Beacom",
 "Gonzaga",
 "Gordon College",
 "Goshen College",
 "Goucher College",
 "Governors State University",
 "Grace College",
 "Graceland University",
 "Grambling State",
 "Grand Canyon",
 "Grand Valley State",
 "Grand View University",
 "Green Bay",
 "Greensboro College",
 "Greenville University",
 "Grinnell College",
 "Grove City College",
 "Guilford College",
 "Gustavus Adolphus College",
 "Gwynedd Mercy University",
 "Hamilton College",
 "Hamline University",
 "Hampton",
 "Hannibal-LaGrange University",
 "Hanover College",
 "Hardin-Simmons University",
 "Harding",
 "Harris-Stowe State University",
 "Hartwick College",
 "Harvard",
 "Harvey Mudd College",
 "Hastings College",
 "Haverford College",
 "Hawaii",
 "Hawaii Hilo",
 "Hawaii Pacific",
 "Heidelberg University",
 "Hendrix College",
 "Hesston College",
 "High Point",
 "Hilbert College",
 "Hiram College",
 "Hobart and William Smith Colleges",
 "Hofstra",
 "Hollins University",
 "Holy Cross",
 "Holy Cross College",
 "Holy Family",
 "Hood College",
 "Hope College",
 "Hope International University",
 "Houghton University",
 "Houston",
 "Houston Christian",
 "Howard",
 "Howard Payne University",
 "Huntingdon College",
 "Huntington University",
 "Husson University",
 "Huston-Tillotson University",
 "IU Indy",
 "IUP",
 "Idaho",
 "Idaho State",
 "Illinois",
 "Illinois College",
 "Illinois Institute of Technology",
 "Illinois State",
 "Illinois Wesleyan University",
 "Immaculata University",
 "Incarnate Word",
 "Indiana",
 "Indiana Institute of Technology",
 "Indiana State",
 "Indiana University Columbus",
 "Indiana University East",
 "Indiana University Kokomo",
 "Indiana University Northwest",
 "Indiana University South Bend",
 "Indiana Wesleyan University",
 "Indianapolis",
 "Iona",
 "Iowa",
 "Iowa State",
 "Ithaca College",
 "Jackson State",
 "Jacksonville",
 "Jacksonville State",
 "James Madison",
 "Jamestown",
 "Jarvis Christian University",
 "Jefferson",
 "Jessup",
 "John Brown University",
 "John Carroll University",
 "Johns Hopkins University",
 "Johnson & Wales University-Charlotte",
 "Johnson & Wales University-Providence",
 "Johnson University",
 "Judson University",
 "Juniata College",
 "Kalamazoo College",
 "Kansas",
 "Kansas City",
 "Kansas State",
 "Kansas Wesleyan University",
 "Kean University",
 "Keiser University",
 "Kennesaw State",
 "Kent State",
 "Kentucky",
 "Kentucky Christian University",
 "Kentucky Wesleyan",
 "Kenyon College",
 "Keuka College",
 "Keystone College",
 "King (TN)",
 "King's College",
 "Knox College",
 "Kutztown",
 "LIU",
 "LSU",
 "LSU Alexandria",
 "LSU Shreveport",
 "La Roche University",
 "La Salle",
 "La Sierra University",
 "LaGrange College",
 "Lafayette",
 "Lake Erie",
 "Lake Forest College",
 "Lakeland University",
 "Lamar",
 "Lancaster Bible College",
 "Lander",
 "Lasell",
 "Lawrence Technological University",
 "Lawrence University",
 "Le Moyne",
 "LeTourneau University",
 "Lebanon Valley College",
 "Lee (TN)",
 "Lees-McRae",
 "Lehigh",
 "Lenoir-Rhyne",
 "Lesley University",
 "Lewis",
 "Lewis & Clark College",
 "Liberty",
 "Life Pacific University",
 "Life University",
 "Lincoln (MO)",
 "Lincoln (PA)",
 "Lincoln Memorial",
 "Lindenwood",
 "Lindsey Wilson University",
 "Linfield University",
 "Lipscomb",
 "Little Rock",
 "Long Beach State",
 "Longwood",
 "Loras College",
 "Louisiana",
 "Louisiana Christian University",
 "Louisiana Tech",
 "Louisiana-Monroe",
 "Louisville",
 "Lourdes University",
 "Loyola (MD)",
 "Loyola Chicago",
 "Loyola Marymount",
 "Lubbock Christian",
 "Luther College",
 "Lycoming College",
 "Lynn",
 "Lyon College",
 "Macalester College",
 "Madonna University",
 "Maine",
 "Maine Maritime Academy",
 "Malone",
 "Manchester University",
 "Manhattan",
 "Manhattanville University",
 "Maranatha Baptist University",
 "Marian University (IN)",
 "Marian University (WI)",
 "Marietta College",
 "Marist",
 "Marquette",
 "Mars Hill",
 "Marshall",
 "Martin Luther College",
 "Mary",
 "Mary Baldwin University",
 "Maryland",
 "Marymount University",
 "Maryville (MO)",
 "Maryville College",
 "Marywood University",
 "Massachusetts College of Liberal Arts",
 "Massachusetts Institute of Technology",
 "Massachusetts Maritime Academy",
 "McDaniel College",
 "McKendree",
 "McMurry University",
 "McNeese",
 "McPherson College",
 "Memphis",
 "Menlo",
 "Mercer",
 "Mercy",
 "Mercyhurst",
 "Meredith College",
 "Merrimack",
 "Messiah University",
 "Methodist University",
 "Metro State Denver",
 "Miami (FL)",
 "Miami (OH)",
 "Michigan",
 "Michigan State",
 "Michigan Tech",
 "Mid-America Christian University",
 "MidAmerica Nazarene University",
 "Middle Georgia State",
 "Middle Tennessee",
 "Middlebury College",
 "Midland University",
 "Midway University",
 "Midwestern State",
 "Millersville",
 "Milligan University",
 "Millikin University",
 "Millsaps College",
 "Milwaukee",
 "Milwaukee School of Engineering",
 "Minnesota",
 "Minnesota Crookston",
 "Minnesota Duluth",
 "Minnesota State Mankato",
 "Minnesota State Moorhead",
 "Minot State",
 "Misericordia University",
 "Mississippi Christian",
 "Mississippi College",
 "Mississippi State",
 "Mississippi University for Women",
 "Missouri",
 "Missouri Baptist University",
 "Missouri S&T",
 "Missouri Southern",
 "Missouri State",
 "Missouri Valley College",
 "Missouri Western",
 "Mitchell",
 "Molloy",
 "Monmouth",
 "Monmouth College",
 "Montana",
 "Montana State Billings",
 "Montclair State University",
 "Montevallo",
 "Montreat College",
 "Moravian University",
 "Morehead State",
 "Morningside University",
 "Mount Aloysius College",
 "Mount Holyoke College",
 "Mount Marty University",
 "Mount Mary University",
 "Mount Mercy University",
 "Mount Olive",
 "Mount Saint Mary College",
 "Mount St. Joseph University",
 "Mount St. Mary's",
 "Mount Vernon Nazarene University",
 "Muhlenberg College",
 "Murray State",
 "Muskingum University",
 "NC State",
 "NJIT",
 "Navy",
 "Nazareth University",
 "Nebraska",
 "Nebraska Wesleyan University",
 "Nebraska at Kearney",
 "Nelson University",
 "Neumann University",
 "Nevada",
 "New College of Florida",
 "New Hampshire",
 "New Haven",
 "New Jersey City University",
 "New Mexico",
 "New Mexico Highlands",
 "New Mexico State",
 "New York University",
 "Newberry",
 "Newman",
 "Niagara",
 "Nicholls",
 "Nichols College",
 "North Alabama",
 "North American University",
 "North Carolina",
 "North Carolina Wesleyan University",
 "North Central College",
 "North Central University",
 "North Dakota",
 "North Dakota State",
 "North Florida",
 "North Georgia",
 "North Greenville",
 "North Park University",
 "North Texas",
 "Northeastern",
 "Northeastern State",
 "Northern Arizona",
 "Northern Colorado",
 "Northern Illinois",
 "Northern Iowa",
 "Northern Kentucky",
 "Northern Michigan",
 "Northern State",
 "Northwest Missouri State",
 "Northwest Nazarene",
 "Northwest University",
 "Northwestern",
 "Northwestern College (Iowa)",
 "Northwestern Oklahoma State",
 "Northwestern State",
 "Northwood",
 "Norwich",
 "Notre Dame",
 "Notre Dame of Maryland University",
 "Nova Southeastern",
 "Oakland",
 "Oakland City University",
 "Oakwood University",
 "Oberlin College",
 "Occidental College",
 "Oglethorpe University",
 "Ohio",
 "Ohio Dominican",
 "Ohio Northern University",
 "Ohio State",
 "Ohio Wesleyan University",
 "Oklahoma",
 "Oklahoma Baptist",
 "Oklahoma Christian",
 "Oklahoma City University",
 "Oklahoma Panhandle State University",
 "Oklahoma State",
 "Oklahoma Wesleyan University",
 "Old Dominion",
 "Ole Miss",
 "Olivet College",
 "Olivet Nazarene University",
 "Omaha",
 "Oral Roberts",
 "Oregon",
 "Oregon Institute of Technology",
 "Oregon State",
 "Ottawa University",
 "Ottawa University Arizona",
 "Otterbein University",
 "Ouachita Baptist",
 "Our Lady of the Lake University",
 "Pace",
 "Pacific",
 "Pacific Lutheran University",
 "Pacific Union College",
 "Pacific University",
 "Palm Beach Atlantic",
 "Park University",
 "Park University Gilbert",
 "Paul Quinn College",
 "Penn",
 "Penn State",
 "Penn State Beaver",
 "Penn State Brandywine",
 "Penn State Hazleton",
 "Penn State Mont Alto",
 "Penn State New Kensington",
 "Penn State Scranton",
 "PennWest California",
 "PennWest Clarion",
 "PennWest Edinboro",
 "Pennsylvania College of Technology",
 "Pennsylvania State University-Penn State Abington",
 "Pennsylvania State University-Penn State Altoona",
 "Pennsylvania State University-Penn State Berks",
 "Pennsylvania State University-Penn State Erie (Behrend College)",
 "Pennsylvania State University-Penn State Harrisburg",
 "Pennsylvania State University-Penn State Schuylkill",
 "Pepperdine",
 "Pfeiffer University",
 "Piedmont University",
 "Pitt-Johnstown",
 "Pittsburgh",
 "Pitzer College",
 "Plymouth State",
 "Point Loma Nazarene",
 "Point Park",
 "Point University",
 "Pomona College",
 "Pomona-Pitzer",
 "Portland",
 "Portland State",
 "Post",
 "Prairie View A&M",
 "Pratt Institute",
 "Presbyterian",
 "Princeton",
 "Principia College",
 "Providence",
 "Purdue",
 "Purdue Fort Wayne",
 "Purdue Northwest",
 "Queens",
 "Queens (CUNY)",
 "Quincy",
 "Quinnipiac",
 "Radford",
 "Ramapo College of New Jersey",
 "Randolph College",
 "Randolph-Macon College",
 "Regent University",
 "Regis (CO)",
 "Reinhardt University",
 "Rensselaer Polytechnic Institute",
 "Rhode Island",
 "Rhodes College",
 "Rice",
 "Richmond",
 "Rider",
 "Rio Grande (University of)",
 "Ripon College",
 "Rivier",
 "Roanoke College",
 "Robert Morris",
 "Roberts Wesleyan",
 "Rochester Christian University",
 "Rochester Institute of Technology",
 "Rockford University",
 "Rockhurst",
 "Rocky Mountain College",
 "Roger Williams University",
 "Rogers State",
 "Rollins",
 "Roosevelt",
 "Rose-Hulman Institute of Technology",
 "Rowan University",
 "Rutgers",
 "Rutgers University-Camden",
 "Rutgers University-Newark",
 "SIU Edwardsville",
 "SMU",
 "SUNY Alfred State",
 "SUNY Buffalo State",
 "SUNY Canton",
 "SUNY Cobleskill",
 "SUNY College at Brockport",
 "SUNY College at Cortland",
 "SUNY College at Geneseo",
 "SUNY Delhi",
 "SUNY Fredonia",
 "SUNY Maritime College",
 "SUNY Morrisville",
 "SUNY New Paltz",
 "SUNY Old Westbury",
 "SUNY Oneonta",
 "SUNY Oswego",
 "SUNY Plattsburgh",
 "SUNY Polytechnic Institute",
 "SUNY Potsdam",
 "SUNY Purchase College",
 "Sacramento State",
 "Sacred Heart",
 "Saginaw Valley State",
 "Saint Ambrose University",
 "Saint Anselm",
 "Saint Elizabeth University",
 "Saint John Fisher University",
 "Saint Joseph's",
 "Saint Leo",
 "Saint Louis",
 "Saint Martin's",
 "Saint Mary's",
 "Saint Mary's College (IN)",
 "Saint Mary's University of Minnesota",
 "Saint Mary-of-the-Woods College",
 "Saint Michael's",
 "Saint Norbert College",
 "Saint Peter's",
 "Saint Vincent College",
 "Saint Xavier University",
 "Salem",
 "Salem College",
 "Salem State University",
 "Salisbury University",
 "Salve Regina University",
 "Sam Houston",
 "Samford",
 "San Diego",
 "San Diego State",
 "San Francisco",
 "San Francisco State",
 "San Jose State",
 "Santa Clara",
 "Sarah Lawrence College",
 "Savannah College of Art and Design",
 "Schreiner University",
 "Scripps College",
 "Seattle",
 "Seattle Pacific",
 "Seton Hall",
 "Seton Hill",
 "Sewanee: The University of the South",
 "Shaw",
 "Shawnee State",
 "Shawnee State University",
 "Shenandoah University",
 "Shepherd",
 "Shippensburg",
 "Shorter",
 "Siena",
 "Siena Heights University",
 "Simmons",
 "Simon Fraser",
 "Simpson College",
 "Simpson University",
 "Sioux Falls",
 "Skidmore College",
 "Slippery Rock",
 "Smith College",
 "Soka University of America",
 "South Alabama",
 "South Carolina",
 "South Carolina Aiken",
 "South Carolina Beaufort",
 "South Carolina State",
 "South Dakota",
 "South Dakota State",
 "South Florida",
 "Southeast Missouri State",
 "Southeastern Louisiana",
 "Southeastern University (Florida)",
 "Southern",
 "Southern Connecticut State",
 "Southern Illinois",
 "Southern Indiana",
 "Southern Miss",
 "Southern Nazarene",
 "Southern New Hampshire",
 "Southern Oregon University",
 "Southern Utah",
 "Southern Virginia University",
 "Southern Wesleyan",
 "Southwest Baptist",
 "Southwest Minnesota State",
 "Southwestern Christian University",
 "Southwestern College (Kansas)",
 "Southwestern Oklahoma State",
 "Southwestern University",
 "Spalding University",
 "Spartanburg Methodist College",
 "Spring Arbor University",
 "Spring Hill",
 "Springfield College",
 "St Lawrence University",
 "St Mary's College of Maryland",
 "St Olaf College",
 "St. Bonaventure",
 "St. Catherine University",
 "St. Cloud State",
 "St. Edward's",
 "St. John's",
 "St. Joseph's University (Brooklyn)",
 "St. Joseph's University (Long Island)",
 "St. Mary's (TX)",
 "St. Thomas",
 "St. Thomas Aquinas",
 "St. Thomas University (Florida)",
 "Stanford",
 "Stanton University",
 "Staten Island",
 "Stephen F. Austin",
 "Stephens College",
 "Sterling College (Kansas)",
 "Stetson",
 "Stevens Institute of Technology",
 "Stevenson University",
 "Stockton University",
 "Stonehill",
 "Stony Brook",
 "Suffolk University",
 "Sul Ross State",
 "Susquehanna University",
 "Swarthmore College",
 "Sweet Briar College",
 "Syracuse",
 "TCU",
 "Tabor College",
 "Talladega College",
 "Tampa",
 "Tarleton State",
 "Taylor University",
 "Temple",
 "Tennessee",
 "Tennessee Tech",
 "Tennessee Wesleyan University",
 "Texas",
 "Texas A&M",
 "Texas A&M International",
 "Texas A&M University-San Antonio",
 "Texas A&M University-Texarkana",
 "Texas A&M University-Victoria",
 "Texas A&M-Corpus Christi",
 "Texas College",
 "Texas Lutheran University",
 "Texas Southern",
 "Texas State",
 "Texas Tech",
 "Texas Wesleyan University",
 "Texas Woman's",
 "The Citadel",
 "The College of New Jersey",
 "The College of St. Scholastica",
 "The College of Wooster",
 "The Evergreen State College",
 "The Master's University",
 "The Sage Colleges",
 "Thiel College",
 "Thomas College",
 "Thomas More",
 "Thomas University",
 "Tiffin",
 "Toledo",
 "Tougaloo College",
 "Towson",
 "Transylvania University",
 "Trevecca Nazarene",
 "Trine University",
 "Trinity Christian College",
 "Trinity College",
 "Trinity University",
 "Trinity Washington University",
 "Troy",
 "Truett McConnell University",
 "Truman State",
 "Tufts University",
 "Tulsa",
 "Tusculum",
 "Tuskegee",
 "UAB",
 "UC Davis",
 "UC Irvine",
 "UC Merced",
 "UC Riverside",
 "UC San Diego",
 "UC Santa Barbara",
 "UC Santa Cruz",
 "UCCS",
 "UCF",
 "UCLA",
 "UConn",
 "UIC",
 "UIS",
 "UMBC",
 "UMSL",
 "UMass",
 "UMass Boston",
 "UMass Dartmouth",
 "UMass Lowell",
 "UNC Asheville",
 "UNC Greensboro",
 "UNC Pembroke",
 "UNC Wilmington",
 "UNLV",
 "USC",
 "USC Upstate",
 "UT Dallas",
 "UT Martin",
 "UT Permian Basin",
 "UT Rio Grande Valley",
 "UT Tyler",
 "UTEP",
 "UTSA",
 "Union (TN)",
 "Union College (NY)",
 "Union Commonwealth University",
 "United States Coast Guard Academy",
 "United States Merchant Marine Academy",
 "University of California-Santa Cruz",
 "University of Chicago",
 "University of Dallas",
 "University of Dubuque",
 "University of Hartford",
 "University of Health Sciences and Pharmacy in St. Louis",
 "University of La Verne",
 "University of Lynchburg",
 "University of Maine at Farmington",
 "University of Maine at Presque Isle",
 "University of Mary Hardin-Baylor",
 "University of Mary Washington",
 "University of Michigan-Dearborn",
 "University of Minnesota-Morris",
 "University of Mobile",
 "University of Mount Union",
 "University of New England",
 "University of Northwestern Ohio",
 "University of Northwestern-St Paul",
 "University of Pikeville",
 "University of Pittsburgh-Bradford",
 "University of Pittsburgh-Greensburg",
 "University of Providence",
 "University of Puget Sound",
 "University of Redlands",
 "University of Rochester",
 "University of Saint Francis (IN)",
 "University of Saint Mary",
 "University of Science and Arts of Oklahoma",
 "University of Scranton",
 "University of St Thomas (TX)",
 "University of St. Francis (IL)",
 "University of Tennessee Southern",
 "University of Valley Forge",
 "University of Wisconsin-Eau Claire",
 "University of Wisconsin-La Crosse",
 "University of Wisconsin-Oshkosh",
 "University of Wisconsin-Platteville",
 "University of Wisconsin-River Falls",
 "University of Wisconsin-Stevens Point",
 "University of Wisconsin-Stout",
 "University of Wisconsin-Superior",
 "University of Wisconsin-Whitewater",
 "University of the Cumberlands",
 "University of the Ozarks",
 "University of the Southwest",
 "Upper Iowa",
 "Ursinus College",
 "Ursuline",
 "Utah",
 "Utah State",
 "Utah Tech",
 "Utah Valley",
 "Utica University",
 "VCU",
 "VMI",
 "Valdosta State",
 "Valparaiso",
 "Vanderbilt",
 "Vanguard",
 "Vassar College",
 "Vermont",
 "Vermont State University-Castleton",
 "Vermont State University-Johnson",
 "Vermont State University-Lyndon",
 "Villanova",
 "Virginia",
 "Virginia State",
 "Virginia Tech",
 "Viterbo University",
 "Wagner",
 "Wake Forest",
 "Waldorf University",
 "Walla Walla University",
 "Walsh",
 "Warner Pacific University",
 "Warner University",
 "Warren Wilson College",
 "Wartburg College",
 "Washburn",
 "Washington",
 "Washington & Jefferson College",
 "Washington Adventist University",
 "Washington College",
 "Washington State",
 "Washington University in St Louis",
 "Washington and Lee University",
 "Wayland Baptist University",
 "Wayne State (MI)",
 "Wayne State (NE)",
 "Waynesburg University",
 "Webber International University",
 "Weber State",
 "Webster University",
 "Wellesley College",
 "Wentworth Institute of Technology",
 "Wesleyan (GA)",
 "Wesleyan University",
 "West Alabama",
 "West Chester",
 "West Florida",
 "West Georgia",
 "West Liberty",
 "West Texas A&M",
 "West Virginia",
 "West Virginia State",
 "West Virginia University Institute of Technology",
 "West Virginia Wesleyan",
 "Westcliff University",
 "Western Carolina",
 "Western Colorado",
 "Western Illinois",
 "Western Kentucky",
 "Western Michigan",
 "Western New England University",
 "Western Oregon",
 "Western Washington",
 "Westfield State University",
 "Westminster (UT)",
 "Westminster College (PA)",
 "Westminster University (MO)",
 "Westmont",
 "Wheaton College (IL)",
 "Wheaton College (MA)",
 "Wheeling",
 "Whitman College",
 "Whittier College",
 "Whitworth University",
 "Widener University",
 "Wiley University",
 "Wilkes University",
 "Willamette University",
 "William & Mary",
 "William Carey University",
 "William Jewell",
 "William Paterson University",
 "William Peace University",
 "William Penn University",
 "William Woods University",
 "Williams Baptist University",
 "Williams College",
 "Wilmington (DE)",
 "Wilmington College",
 "Wilson College",
 "Wingate",
 "Winona State",
 "Winthrop",
 "Wisconsin",
 "Wisconsin Lutheran College",
 "Wisconsin-Parkside",
 "Wittenberg University",
 "Wofford",
 "Worcester Polytechnic Institute",
 "Worcester State University",
 "Wright State",
 "Wyoming",
 "Xavier",
 "Xavier University of Louisiana",
 "Yale",
 "Yeshiva University",
 "York College of Pennsylvania",
 "York University (Nebraska)",
 "Young Harris",
 "Youngstown State"
];
