/**
 * Derive the pinned V2 ability scale from the live programme distribution.
 *
 * WHY A PINNED FILE AND NOT A RUNTIME QUERY. The 1-10 slider is an operator's
 * judgement of an athlete. What that judgement MEANS - "rating 8 is a Division
 * I player" - is a statement about where the athlete sits relative to the
 * programmes we hold. If the scale were recomputed from whatever is in the
 * database at request time, then importing forty NJCAA programmes would move
 * every athlete's meaning without anyone deciding to, and no test would fail.
 *
 * So the scale is DATA, generated here, reviewed, and committed. This script
 * is the only thing allowed to produce it, and `--check` is what tells us the
 * live distribution has drifted far enough that the scale should be reviewed.
 * `--check` never rewrites: a distribution change is a decision, not an event.
 *
 * QUANTILE DEFINITION. Nearest-rank (Hyndman-Fan type 1): the score at
 * index ceil(p * n) - 1 of the ascending vector. Pinned in the output so that
 * a regeneration under a different definition is visible as a definition
 * change rather than as drift.
 *
 *   node server/scripts/calibrateAbilityScale.js --write
 *   node server/scripts/calibrateAbilityScale.js --check
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../../shared/matching/v2/calibration/abilityScale.data.json');

/**
 * The percentile each integer rating is declared to mean. HEURISTIC: this
 * allocation is a design choice, not a measurement. It is chosen so that each
 * rating lands on an interpretable division mix and so that 8, 9 and 10
 * separate the Division I tail rather than crowding the top six percent, which
 * is what `ability * 10` did.
 */
const PERCENTILE_TARGETS = [2, 8, 18, 32, 48, 64, 78, 89, 96, 99.5];

const SPORTS = ['mens-soccer', 'womens-soccer'];

/** The window, in percentile points either side, that the division mix describes. */
const MIX_WINDOW = 3;

const QUANTILE_METHOD = 'nearest-rank';

function quantile(sorted, p) {
  const i = Math.min(sorted.length - 1, Math.max(0, Math.ceil((p / 100) * sorted.length) - 1));
  return sorted[i];
}

function digestOf(scores) {
  return crypto.createHash('sha256')
    .update(scores.map((s) => s.toFixed(2)).join(','))
    .digest('hex')
    .slice(0, 16);
}

function divisionMix(rows, sorted, p) {
  const lo = quantile(sorted, Math.max(0, p - MIX_WINDOW));
  const hi = quantile(sorted, Math.min(100, p + MIX_WINDOW));
  const band = rows.filter((r) => r.soccer_score >= lo && r.soccer_score <= hi);
  const counts = new Map();
  for (const r of band) counts.set(r.division, (counts.get(r.division) || 0) + 1);
  return Object.fromEntries([...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([d, n]) => [d, Number((n / band.length).toFixed(3))]));
}

function buildSport(rows) {
  const sorted = rows.map((r) => r.soccer_score).sort((a, b) => a - b);
  return {
    programmes: sorted.length,
    min: sorted[0],
    max: sorted[sorted.length - 1],
    sourceDistributionDigest: digestOf(sorted),
    divisionCounts: rows.reduce((acc, r) => { acc[r.division] = (acc[r.division] || 0) + 1; return acc; }, {}),
    // The full ascending vector. Pinned rather than summarised so that the
    // digest is a digest of exactly what the scale reads, and so that the
    // programme-percentile lookup is the real empirical CDF rather than an
    // interpolation of an interpolation.
    distribution: sorted.map((s) => Number(s.toFixed(2))),
    ratings: PERCENTILE_TARGETS.map((p, i) => ({
      rating: i + 1,
      percentile: p,
      soccerScore: Number(quantile(sorted, p).toFixed(2)),
      divisionMix: divisionMix(rows, sorted, p),
    })),
  };
}

function loadRows(db, sport) {
  return db.prepare(`
    SELECT soccer_score, division
      FROM colleges
     WHERE sport = ? AND active = 1 AND soccer_score IS NOT NULL
  `).all(sport);
}

function build(db) {
  const sports = {};
  for (const sport of SPORTS) {
    const rows = loadRows(db, sport);
    if (rows.length < 100) {
      console.error(`Refusing to calibrate ${sport}: only ${rows.length} scored programmes.`);
      console.error('A scale derived from a partial pool would silently redefine every rating.');
      process.exit(3);
    }
    sports[sport] = buildSport(rows);
  }
  return {
    calibrationId: 'ability-scale-2026-09-19',
    createdAt: '2026-09-19',
    quantileMethod: QUANTILE_METHOD,
    mixWindowPercentilePoints: MIX_WINDOW,
    percentileTargets: PERCENTILE_TARGETS,
    note: 'Generated by server/scripts/calibrateAbilityScale.js. Do not hand-edit.',
    sports,
  };
}

async function main() {
  const args = process.argv.slice(2);
  const write = args.includes('--write');
  const check = args.includes('--check');
  if (write === check) {
    console.error('Usage: calibrateAbilityScale.js --write | --check');
    console.error('  --write  regenerate the pinned scale from the live distribution');
    console.error('  --check  report whether the live distribution still matches the pin');
    process.exit(2);
  }

  const { default: db } = await import('../db/client.js');
  const built = build(db);

  if (write) {
    fs.writeFileSync(OUT, `${JSON.stringify(built, null, 2)}\n`);
    console.log(`Wrote ${path.relative(process.cwd(), OUT)}`);
    for (const sport of SPORTS) {
      const s = built.sports[sport];
      console.log(`  ${sport}: ${s.programmes} programmes, digest ${s.sourceDistributionDigest}`);
      for (const r of s.ratings) {
        const mix = Object.entries(r.divisionMix).slice(0, 3)
          .map(([d, f]) => `${d} ${Math.round(f * 100)}%`).join(', ');
        console.log(`    ${String(r.rating).padStart(2)} p${r.percentile} -> ${r.soccerScore}  (${mix})`);
      }
    }
    return;
  }

  const pinned = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  let drift = 0;
  for (const sport of SPORTS) {
    const was = pinned.sports[sport];
    const now = built.sports[sport];
    if (was.sourceDistributionDigest === now.sourceDistributionDigest) {
      console.log(`${sport}: unchanged (${now.programmes} programmes)`);
      continue;
    }
    drift += 1;
    console.log(`${sport}: DISTRIBUTION MOVED`);
    console.log(`  programmes ${was.programmes} -> ${now.programmes}`);
    for (const r of now.ratings) {
      const before = was.ratings.find((x) => x.rating === r.rating);
      const dominant = (m) => Object.entries(m).sort((a, b) => b[1] - a[1])[0]?.[0];
      const moved = dominant(before.divisionMix) !== dominant(r.divisionMix);
      if (before.soccerScore !== r.soccerScore || moved) {
        console.log(`  rating ${r.rating}: ${before.soccerScore} -> ${r.soccerScore}`
          + `${moved ? `  DOMINANT DIVISION MOVED ${dominant(before.divisionMix)} -> ${dominant(r.divisionMix)}` : ''}`);
      }
    }
  }
  if (drift) {
    console.log('');
    console.log('The scale has NOT been rewritten. A rating means what it means because');
    console.log('someone decided; regenerate with --write only as a reviewed decision.');
    process.exit(1);
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
