/**
 * The measured playing norms, and the heuristics beside them.
 *
 * DERIVED values come from playingNorms.data.json, generated by
 * server/scripts/derivePlayingNorms.js. HEURISTIC values are named below.
 */
import norms from './calibration/playingNorms.data.json' with { type: 'json' };

export const PLAYING_NORMS_ID = norms.playingNormsId;
export const PLAYING_NORMS_DIGEST = norms.digest;
export const PLAYING_NORMS = Object.freeze(norms);

/**
 * How widely a programme shares the minutes at a position, resolved most
 * specific first.
 *
 *   programme  needs 2 readable seasons. USED - unlike A7.3's fill propensity,
 *              this survives a split-half test at r = 0.43-0.61 within
 *              position, because it measures how a coach uses a squad rather
 *              than who happened to graduate.
 *   division   needs 30 programme-seasons.
 *   sport      always available.
 */
export function playingShareFor({ sport, division, position, programme }) {
  const p = String(position || '').toUpperCase();
  const at = (level, key) => {
    const hit = norms[level]?.[key];
    return hit ? { ...hit, level, key } : null;
  };
  return at('programme', `${sport}|${programme}|${p}`)
    ?? at('division', `${sport}|${division}|${p}`)
    ?? at('sport', `${sport}|${p}`)
    ?? null;
}

/** The p10/median/p90 a raw share is read against, per sport and position. */
export function playingScale(sport, position) {
  return norms.scale?.[`${sport}|${String(position || '').toUpperCase()}`] ?? null;
}

/**
 * Where a programme's trajectory is treated as clearly improving or declining.
 *
 * HEURISTIC, anchored on the measured spread: the change in win rate between
 * the two most recent seasons runs from -0.17 at the tenth percentile to +0.18
 * at the ninetieth, so +/- 0.3 is comfortably outside the range almost every
 * programme occupies and the map does not saturate on ordinary variation.
 */
export const TRAJECTORY_SATURATION = 0.3;

/**
 * Component weights inside the objective half of the layer. HEURISTIC.
 *
 * Playing opportunity leads because it is the one thing an athlete is
 * unambiguously there for; trajectory is real evidence and a smaller part of
 * the answer.
 */
export const VALUE_WEIGHTS = Object.freeze({
  playingOpportunity: 0.65,
  programmeTrajectory: 0.35,
});

/**
 * How far BELOW an athlete's own calibrated level a programme must sit before
 * an athlete who cares most about competitive level considers it no longer
 * the standard they are after.
 *
 * HEURISTIC, in percentile points of programme strength. 0.35 is a third of
 * the pool: for a rating-9 athlete at the 96th percentile it reaches down to
 * about the 61st, which spans Division I to mid Division II - a step down
 * anybody would recognise as one.
 */
export const COMPETITIVE_LEVEL_SPAN = 0.35;

/**
 * How much an EXPLICIT 1-5 preference may move the weight of the one
 * component it owns.
 *
 * HEURISTIC, and larger than PRIORITY_LIFT on purpose. The legacy ranking is
 * an ordering of six tokens and says only that one matters more than another;
 * these fields ask a direct question and get a direct answer, so "the most
 * important thing" is allowed to carry nearly twice the default weight and
 * "not important" about a fifth of it.
 */
export const AMBITION_LIFT = 0.8;

/** Weight carried by a declared preference, when one exists. HEURISTIC. */
export const PREFERENCE_WEIGHTS = Object.freeze({
  majorFit: 0.4,
  locationFit: 0.3,
  athleticOutcome: 0.3,
  /**
   * A7.7.5. Matched to athleticOutcome, because the two ask the same shape of
   * question about different axes - what standard of programme, and what
   * standard of institution - and nothing measured justifies preferring one.
   *
   * Selected on a plateau rather than at an optimum: across 0.20 to 0.40 the
   * top-25 Jaccard between priority 1 and priority 5 moves smoothly and the
   * recruitability guard holds; above 0.40 academic reaches begin to arrive
   * in a developmental athlete's list. HEURISTIC, UNCALIBRATED TO OUTCOMES.
   */
  academicStrengthFit: 0.3,
});

/**
 * How much an athlete's stated priority may move the weight of the ONE
 * component it maps onto.
 *
 * HEURISTIC. A criterion ranked first is multiplied by 1 + lift, one ranked
 * last by 1 - lift, interpolating between. Deliberately modest: a ranking is
 * an ordering of six things, not a statement of how much more one matters.
 */
export const PRIORITY_LIFT = 0.5;

/**
 * Which V1 criterion rankings survive into V2 Opportunity, and what they move.
 *
 * Only two of the six. `athletic` belongs to Coach Recruitability and
 * `affordability` to Financial Viability, and letting a priority reach across
 * layers would let an athlete's stated preference change whether a coach wants
 * them. `programQuality` was dropped as a criterion at A5.1 and does not come
 * back. `geography` maps to a component that is NOT_APPLICABLE today, so the
 * mapping exists and currently moves nothing.
 */
export const PRIORITY_MAP = Object.freeze({
  roster: 'playingOpportunity',
  academic: 'majorFit',
  geography: 'locationFit',
});

/** Priorities that must never reach this layer, named so the guard can say why. */
export const FOREIGN_PRIORITIES = Object.freeze({
  athletic: 'Coach Recruitability',
  affordability: 'Financial Viability',
  programQuality: 'dropped as a criterion at A5.1',
});

/**
 * Coverage the layer must reach to be scoreable.
 *
 * A6.2 proposed 0.35. Kept, and it means something different here than in the
 * other layers: playing opportunity alone carries 0.65 of the applicable
 * weight when no preference is declared, so the floor reduces to requiring the
 * objective half. What it rejects is a programme where only trajectory is
 * readable - a win-rate change is not on its own an answer to whether an
 * opportunity is worth having.
 */
export const OPPORTUNITY_COVERAGE_FLOOR = 0.35;
