/**
 * The measured playing norms, and the heuristics beside them.
 *
 * DERIVED values come from playingNorms.data.json, generated by
 * server/scripts/derivePlayingNorms.js. HEURISTIC values are named below.
 */
import norms from './calibration/playingNorms.data.json' with { type: 'json' };

export const PLAYING_NORMS_ID = norms.playingNormsId;
export const PLAYING_NORMS_DIGEST = norms.digest;
export const PLAYING_NORMS = Object.freeze(norms);

/**
 * How widely a programme shares the minutes at a position, resolved most
 * specific first.
 *
 *   programme  needs 2 readable seasons. USED - unlike A7.3's fill propensity,
 *              this survives a split-half test at r = 0.43-0.61 within
 *              position, because it measures how a coach uses a squad rather
 *              than who happened to graduate.
 *   division   needs 30 programme-seasons.
 *   sport      always available.
 */
export function playingShareFor({ sport, division, position, programme }) {
  const p = String(position || '').toUpperCase();
  const at = (level, key) => {
    const hit = norms[level]?.[key];
    return hit ? { ...hit, level, key } : null;
  };
  return at('programme', `${sport}|${programme}|${p}`)
    ?? at('division', `${sport}|${division}|${p}`)
    ?? at('sport', `${sport}|${p}`)
    ?? null;
}

/** The p10/median/p90 a raw share is read against, per sport and position. */
export function playingScale(sport, position) {
  return norms.scale?.[`${sport}|${String(position || '').toUpperCase()}`] ?? null;
}

/**
 * Where a programme's trajectory is treated as clearly improving or declining.
 *
 * HEURISTIC, anchored on the measured spread: the change in win rate between
 * the two most recent seasons runs from -0.17 at the tenth percentile to +0.18
 * at the ninetieth, so +/- 0.3 is comfortably outside the range almost every
 * programme occupies and the map does not saturate on ordinary variation.
 */
export const TRAJECTORY_SATURATION = 0.3;

/**
 * Component weights inside the objective half of the layer. HEURISTIC.
 *
 * Playing opportunity leads because it is the one thing an athlete is
 * unambiguously there for; trajectory is real evidence and a smaller part of
 * the answer.
 */
export const VALUE_WEIGHTS = Object.freeze({
  playingPathway: 0.65,
  programmeTrajectory: 0.35,
});

/**
 * PLAYING PATHWAY, and the four constants it needs.
 *
 * The layer asks "how favourable does this programme's positional pathway look
 * for this athlete, given the competition projected to be there when they
 * arrive and how the programme has historically used players at this
 * position". It is built from two facts that are deliberately kept apart:
 *
 *   RETURNING COMPETITION  how crowded this position is projected to be
 *   SQUAD ROTATION         how widely this coach has shared minutes here
 *
 * NEITHER IS A PROBABILITY. Nothing here estimates minutes, a chance of
 * starting or a likelihood of an offer; we hold no outcome data that could fit
 * one. These are declared heuristics, chosen from the A7.8.2 robustness
 * surface rather than fitted.
 */

/**
 * What a returner we could place as a SQUAD player counts for, against a
 * returning starter's 1.0.
 *
 * HEURISTIC, selected on the plateau. Across four season transitions and both
 * sports, a squad player at season T starts at T+1 about 18-20% of the time
 * against a starter's 85-86%, so they are real competition and not equal
 * competition. Between 0.3 and 0.5 the universe response moves by about 0.02
 * of rank correlation, which is why this is a region rather than a point.
 */
export const RETURNING_SQUAD_WEIGHT = 0.4;

/**
 * What a returner whose role we could NOT place counts for.
 *
 * HEURISTIC, and anchored rather than assumed. Following players whose role
 * was unreadable at season T into T+1, they went on to start 17.8% of the time
 * in the men's game and 25.5% in the women's - against 18.0% and 20.0% for
 * players we could place as squad, and 84.8% and 86.4% for starters. On a
 * scale where squad sits at 0 and starter at 1, an unplaceable returner sits
 * at -0.00 and +0.08.
 *
 * So the evidence says they behave like squad players. This sits a little
 * ABOVE the squad weight anyway, for two reasons: the measurement can only see
 * the unplaceable players who later became readable, which flatters them
 * toward the starter end; and asserting that doubt IS squad membership claims
 * something we did not measure. What it must never be is zero - a player we
 * cannot describe is still standing in front of the athlete.
 */
export const RETURNING_UNKNOWN_WEIGHT = 0.5;

/**
 * The pressure at which returning competition halves the component.
 *
 * HEURISTIC, in STARTING UNITS: pressure 1.0 means one full starting line's
 * worth of weighted returners at this position, so the constant is read as
 * "three quarters of a starting line halves it". The map is
 * `1 / (1 + pressure / 0.75)`, chosen over linear and exponential families
 * because it never clamps: a position with four starting units of returners
 * still scores 0.158 against six units' 0.111, and the two remain orderable.
 * A linear map reaches zero and stops telling crowded programmes apart.
 */
export const COMPETITION_HALF_PRESSURE = 0.75;

/**
 * How much of Playing Pathway is projected competition rather than historical
 * rotation.
 *
 * HEURISTIC. Returning competition is specific to this athlete's entry year
 * and answers the question directly; rotation is a stable programme trait and
 * context. Across the surface, 50/50 gives a rank response of 0.37-0.41,
 * 60/40 gives 0.40-0.45 and 70/30 gives 0.43-0.50 - but 70/30 also raises the
 * number of programmes moved at playing priority 1 from about 230 to about
 * 290, which is louder than a near-inert preference should be. 60/40 is the
 * centre of the region that responds without becoming noisy.
 */
export const COMPETITION_SHARE = 0.6;

/**
 * How far BELOW an athlete's own calibrated level a programme must sit before
 * an athlete who cares most about competitive level considers it no longer
 * the standard they are after.
 *
 * HEURISTIC, in percentile points of programme strength. 0.35 is a third of
 * the pool: for a rating-9 athlete at the 96th percentile it reaches down to
 * about the 61st, which spans Division I to mid Division II - a step down
 * anybody would recognise as one.
 */
export const COMPETITIVE_LEVEL_SPAN = 0.35;

/**
 * How much an EXPLICIT 1-5 preference may move the weight of the one
 * component it owns.
 *
 * HEURISTIC, and larger than PRIORITY_LIFT on purpose. The legacy ranking is
 * an ordering of six tokens and says only that one matters more than another;
 * these fields ask a direct question and get a direct answer, so "the most
 * important thing" is allowed to carry nearly twice the default weight and
 * "not important" about a fifth of it.
 */
export const AMBITION_LIFT = 0.8;

/** Weight carried by a declared preference, when one exists. HEURISTIC. */
export const PREFERENCE_WEIGHTS = Object.freeze({
  /**
   * -- A7.23: WHY A DECLARED MAJOR IS WORTH MORE THAN A PATHWAY -------------
   *
   * Raised from 0.4, which A7.19 measured to be doing almost nothing. For the
   * academic-priority athlete, programmes offering the requested major were
   * 32% of the universe and 30% of the first hundred - INDISTINGUISHABLE FROM
   * THE BASE RATE. The signal scored, it ordered correctly, and it changed
   * essentially nothing: the enrichment was +12 points at rank 25 and gone by
   * rank 50.
   *
   * -- WHY RE-WEIGHTING WORKS HERE AND NOT FOR THE PREFERENCES --------------
   *
   * A7.20 established that widening a preference's weight range inside
   * Opportunity does nothing at all: eight times the range moved playing
   * churn from 8 to 12. Opportunity renormalises over its scored components,
   * so `dO/dw = W(v - mean_other) / (w + W)^2` - the leverage is the
   * component's DEVIATION from the others, and `playingPathway` (0.582) and
   * `academicStrengthFit` (0.607) sit almost exactly on the weighted mean of
   * their neighbours (0.512, 0.509). There is nothing for extra weight to
   * act on.
   *
   * `majorFit` is binary. Its deviation is +0.40 or -0.60, never near zero,
   * so weight converts directly into ordering. The same arithmetic that makes
   * the preferences inert makes this work.
   *
   * -- WHY 1.2, AND WHY IT IS NOT A FILTER ---------------------------------
   *
   * A7.22 swept 0.4 through 2.4 on both sports. At 2.4 the women's first
   * twenty-five held NO non-matching programme, which is a filter wearing a
   * weight's clothing. At 1.2 the enrichment is +40 and +52 points at rank 25
   * and +10 and +22 at rank 100, 97% and 99% of matching programmes improve,
   * and 57 and 41 NON-matching programmes remain in the first hundred with
   * the best of them ranked tenth and fifteenth. A programme that does not
   * offer the major still outranks most that do when its other evidence is
   * stronger, which is the requirement.
   *
   * IT IS LARGER THAN playingPathway's 0.65 AND THAT IS NOT A CLAIM THAT A
   * MAJOR MATTERS MORE THAN PLAYING TIME. The two signals have different
   * distributions and the weights are not comparable: one is a binary fact
   * about a course catalogue, the other a continuous estimate that clusters.
   *
   * NOT conditional on academicStrengthPriority. "I want Engineering" and
   * "academic strength matters to me" are different statements, and the
   * effect is present at priority 1: +12 and +26 points of enrichment.
   *
   * THE EVIDENCE IS STILL BINARY. Nothing here makes it more certain; it
   * makes it count for what it already says.
   */
  majorFit: 1.2,
  locationFit: 0.3,
  athleticOutcome: 0.3,
  /**
   * A7.7.5. Matched to athleticOutcome, because the two ask the same shape of
   * question about different axes - what standard of programme, and what
   * standard of institution - and nothing measured justifies preferring one.
   *
   * Selected on a plateau rather than at an optimum: across 0.20 to 0.40 the
   * top-25 Jaccard between priority 1 and priority 5 moves smoothly and the
   * recruitability guard holds; above 0.40 academic reaches begin to arrive
   * in a developmental athlete's list. HEURISTIC, UNCALIBRATED TO OUTCOMES.
   */
  academicStrengthFit: 0.3,
});

/**
 * How much an athlete's stated priority may move the weight of the ONE
 * component it maps onto.
 *
 * HEURISTIC. A criterion ranked first is multiplied by 1 + lift, one ranked
 * last by 1 - lift, interpolating between. Deliberately modest: a ranking is
 * an ordering of six things, not a statement of how much more one matters.
 */
export const PRIORITY_LIFT = 0.5;

/**
 * Which V1 criterion rankings survive into V2 Opportunity, and what they move.
 *
 * Only two of the six. `athletic` belongs to Coach Recruitability and
 * `affordability` to Financial Viability, and letting a priority reach across
 * layers would let an athlete's stated preference change whether a coach wants
 * them. `programQuality` was dropped as a criterion at A5.1 and does not come
 * back. `geography` maps to a component that is NOT_APPLICABLE today, so the
 * mapping exists and currently moves nothing.
 */
export const PRIORITY_MAP = Object.freeze({
  roster: 'playingPathway',
  academic: 'majorFit',
  geography: 'locationFit',
});

/** Priorities that must never reach this layer, named so the guard can say why. */
export const FOREIGN_PRIORITIES = Object.freeze({
  athletic: 'Coach Recruitability',
  affordability: 'Financial Viability',
  programQuality: 'dropped as a criterion at A5.1',
});

/**
 * Coverage the layer must reach to be scoreable.
 *
 * A6.2 proposed 0.35. Kept, and it means something different here than in the
 * other layers: playing opportunity alone carries 0.65 of the applicable
 * weight when no preference is declared, so the floor reduces to requiring the
 * objective half. What it rejects is a programme where only trajectory is
 * readable - a win-rate change is not on its own an answer to whether an
 * opportunity is worth having.
 */
export const OPPORTUNITY_COVERAGE_FLOOR = 0.35;
