/**
 * The measured positional norms, and the heuristics that sit beside them.
 *
 * Everything DERIVED comes from positionalNorms.data.json, generated by
 * server/scripts/derivePositionalNorms.js and pinned for the same reason the
 * ability scale is pinned: what "a place at this position" means must not
 * change because a roster import landed.
 *
 * Everything HEURISTIC is named as such below, has a stated meaning, and is
 * exercised by the sensitivity run.
 */
import norms from './calibration/positionalNorms.data.json' with { type: 'json' };

export const POSITIONS = Object.freeze(['GOALKEEPER', 'DEFENSE', 'MIDFIELD', 'FORWARD']);
export const NORMS_ID = norms.normsId;
export const NORMS_DIGEST = norms.digest;
export const NORMS = Object.freeze(norms);

/**
 * How many players hold a starting place at a position. DERIVED.
 *
 * GOALKEEPERS ARE INCLUDED, and the measurement is why. Across 2,546 men's and
 * 3,510 women's programme-seasons the median is 1, the interquartile range is
 * ZERO, and 87% / 84% of programme-seasons land exactly on it - by a distance
 * the best-determined figure of any position, where defence, midfield and
 * attack land on their own medians only 24-31% of the time.
 *
 * This is NOT the football convention that one goalkeeper plays at a time. It
 * is the same measurement applied to every position, and goalkeepers happen to
 * be where it is sharpest. `positionUtilisation` excludes them because it
 * describes how widely minutes are SPREAD and a position with one player has
 * no spread; that degeneracy is exactly what makes the COUNT well determined.
 */
export function typicalStarters(sport, position) {
  const entry = norms.typicalStarters?.[sport]?.[String(position || '').toUpperCase()];
  return entry ? entry.typicalStarters : null;
}

export function typicalStartersEvidence(sport, position) {
  return norms.typicalStarters?.[sport]?.[String(position || '').toUpperCase()] ?? null;
}

/**
 * Given a starting place vacated at a position, how often a newcomer holds a
 * starting place there the next season. DERIVED.
 *
 * Resolved most specific first, and the levels exist so the hierarchy is real
 * when the data becomes real:
 *
 *   programme-position  needs 8 observations. NOTHING REACHES THIS TODAY.
 *                       We hold three season transitions, so a programme has
 *                       at most three; the spread of programme rates around
 *                       the pooled rate is what three coin flips produce, and
 *                       reading it as programme character would be reading
 *                       noise into a score.
 *   division-position   needs 30. Real and used: men's goalkeeping runs 0.585
 *                       at D2 against 0.458 at D3.
 *   sport-position      always available. 0.51 goalkeeper against 0.85 midfield
 *                       is the single largest positional effect measured.
 *
 * This is an evidence-backed fallback carrying its own numerator, denominator
 * and level - not V1's neutral 0.5, which was chosen because it was the middle.
 */
export function fillPropensity({ sport, division, position, programme }) {
  const p = String(position || '').toUpperCase();
  const at = (level, key) => {
    const hit = norms.fillPropensity?.[level]?.[key];
    return hit ? { ...hit, level, key } : null;
  };
  return at('programme', `${sport}|${programme}|${p}`)
    ?? at('division', `${sport}|${division}|${p}`)
    ?? at('sport', `${sport}|${p}`)
    ?? null;
}

/**
 * The slope of the athletic-plausibility logistic, in percentile points.
 *
 * HEURISTIC. `s` is the scale over which a coach's interest changes: at s =
 * 0.12 an athlete ten percentile points below a programme scores 0.30 and one
 * thirty points below scores 0.08. Translated into real programmes, a rating-8
 * athlete is at California, a reach at UNC Greensboro (-0.05) and a stretch at
 * Maryland (-0.10).
 *
 * Not fitted, and deliberately not fittable from destination recall: where an
 * athlete ended up is decided by who recruited and offered first as much as by
 * whether a coach would have been interested. Chosen instead for the shape the
 * sensitivity run reports - s <= 0.08 turns the curve into a filter wearing a
 * score's clothing, s >= 0.20 leaves an implausible reach scoring 0.18.
 */
export const PLAUSIBILITY_SLOPE = 0.12;

/**
 * Where the logistic passes one half.
 *
 * HEURISTIC, and held at zero on purpose: parity. An athlete at exactly a
 * programme's own level is an even proposition. Moving it would be a claim
 * about how far above or below their level coaches typically sign, and no
 * measurement here supports one - the only data that could fit it is
 * destination recall, which answers a different question.
 */
export const PLAUSIBILITY_MIDPOINT = 0;

/**
 * The share of athletic plausibility that survives when no other recruiting
 * evidence favours the athlete.
 *
 * HEURISTIC. A programme with no opening still recruits - squads carry depth,
 * and a coach who rates a player finds a place. phi is how much of that
 * survives: at 0.35 an at-level athlete with no opportunity scores 0.35 of
 * their plausibility rather than nothing.
 */
export const CORE_FLOOR = 0.35;

/**
 * How strongly an already-recruited arrival claims a vacated place.
 *
 * HEURISTIC. Below 1 because an arrival is not a one-for-one replacement: a
 * class is recruited against a squad, not against a specific departure.
 */
export const ARRIVAL_CLAIM_WEIGHT = 0.6;

/**
 * The most of a vacated place that claims may absorb.
 *
 * HEURISTIC. Caps the reduction so that arrivals and returning depth can
 * strongly demote an opening and never delete it - a squad that recruited
 * four midfielders may still take a fifth, and a model that says otherwise is
 * asserting knowledge of a coach's list that we do not have.
 */
export const MAX_CLAIM_SHARE = 0.75;

/** Component weights inside the recruitability core. HEURISTIC. */
export const CORE_WEIGHTS = Object.freeze({
  positionalOpportunity: 0.7,
  internationalPropensity: 0.3,
});

/**
 * Coverage the core must reach before recruitability is scoreable at all.
 *
 * HEURISTIC, and it binds where it matters: for an international athlete it
 * rejects a programme we know only the international history of, because
 * "they sign overseas players" is not an answer to "would they want this one".
 * For a domestic athlete international propensity is NOT_APPLICABLE, so
 * positional opportunity carries the whole core and the floor reduces to
 * requiring it.
 */
export const RECRUITABILITY_COVERAGE_FLOOR = 0.6;
