/**
 * The measured positional norms, and the heuristics that sit beside them.
 *
 * Everything DERIVED comes from positionalNorms.data.json, generated by
 * server/scripts/derivePositionalNorms.js and pinned for the same reason the
 * ability scale is pinned: what "a place at this position" means must not
 * change because a roster import landed.
 *
 * Everything HEURISTIC is named as such below, has a stated meaning, and is
 * exercised by the sensitivity run.
 */
import norms from './calibration/positionalNorms.data.json' with { type: 'json' };

export const POSITIONS = Object.freeze(['GOALKEEPER', 'DEFENSE', 'MIDFIELD', 'FORWARD']);
export const NORMS_ID = norms.normsId;
export const NORMS_DIGEST = norms.digest;
export const NORMS = Object.freeze(norms);

/**
 * How many players hold a starting place at a position. DERIVED.
 *
 * GOALKEEPERS ARE INCLUDED, and the measurement is why. Across 2,546 men's and
 * 3,510 women's programme-seasons the median is 1, the interquartile range is
 * ZERO, and 87% / 84% of programme-seasons land exactly on it - by a distance
 * the best-determined figure of any position, where defence, midfield and
 * attack land on their own medians only 24-31% of the time.
 *
 * This is NOT the football convention that one goalkeeper plays at a time. It
 * is the same measurement applied to every position, and goalkeepers happen to
 * be where it is sharpest. `positionUtilisation` excludes them because it
 * describes how widely minutes are SPREAD and a position with one player has
 * no spread; that degeneracy is exactly what makes the COUNT well determined.
 */
export function typicalStarters(sport, position) {
  const entry = norms.typicalStarters?.[sport]?.[String(position || '').toUpperCase()];
  return entry ? entry.typicalStarters : null;
}

export function typicalStartersEvidence(sport, position) {
  return norms.typicalStarters?.[sport]?.[String(position || '').toUpperCase()] ?? null;
}

/**
 * Given a starting place vacated at a position, how often a newcomer holds a
 * starting place there the next season. DERIVED.
 *
 * Resolved most specific first, and the levels exist so the hierarchy is real
 * when the data becomes real:
 *
 *   programme-position  needs 8 observations. NOTHING REACHES THIS TODAY.
 *                       We hold three season transitions, so a programme has
 *                       at most three; the spread of programme rates around
 *                       the pooled rate is what three coin flips produce, and
 *                       reading it as programme character would be reading
 *                       noise into a score.
 *   division-position   needs 30. Real and used: men's goalkeeping runs 0.585
 *                       at D2 against 0.458 at D3.
 *   sport-position      always available. 0.51 goalkeeper against 0.85 midfield
 *                       is the single largest positional effect measured.
 *
 * This is an evidence-backed fallback carrying its own numerator, denominator
 * and level - not V1's neutral 0.5, which was chosen because it was the middle.
 */
export function fillPropensity({ sport, division, position, programme }) {
  const p = String(position || '').toUpperCase();
  const at = (level, key) => {
    const hit = norms.fillPropensity?.[level]?.[key];
    return hit ? { ...hit, level, key } : null;
  };
  return at('programme', `${sport}|${programme}|${p}`)
    ?? at('division', `${sport}|${division}|${p}`)
    ?? at('sport', `${sport}|${p}`)
    ?? null;
}

/**
 * ATHLETIC RECRUITING COMPATIBILITY, and the three numbers that shape it.
 *
 * The question is "on athletic level alone, how compatible is this athlete
 * with the level this programme recruits at". It is a DECLARED HEURISTIC
 * COMPATIBILITY FACTOR, not a probability: nothing here is estimated from
 * coach replies, offers or any other outreach response, because none are held.
 * When that data exists it may replace these constants; until then they are a
 * stated design position and should be read as one.
 *
 * -- WHY THE SHAPE IS ASYMMETRIC --------------------------------------------
 *
 * The axis is percentiles of the programme-strength distribution, and that
 * distribution is not evenly spread. For a men's rating-9 athlete the whole
 * span from their own level to the strongest programme in the country is 0.039
 * percentile points, while the span from their level to a mid-table Division
 * III side is 0.58 - about eleven times less resolution above them than below.
 * A symmetric curve therefore cannot tell "at level" from "a genuine reach"
 * without also flattening everything below; every symmetric alternative tested
 * in A7.7.13 either left at-level programmes compressed or carried Stanford
 * into the outreach slice alongside them.
 *
 * An asymmetric curve can, because it spends its steepness in exactly those
 * few points. THIS IS COMPENSATION FOR A KNOWN LIMITATION OF THE REFERENCE
 * AXIS, not a discovery about how coaches behave. If the axis is ever replaced
 * with a measure of recruiting competition rather than programme density,
 * these three constants must be derived again from scratch.
 */

/**
 * Compatibility at the athlete's own level.
 *
 * HEURISTIC. The ability scale already declares what a rating means: a men's
 * rating 9 IS the 96th percentile, equivalent to a programme scoring 83.58. An
 * athlete standing at the level the calibration places them is an ordinary
 * member of that programme's recruiting class, so this is high rather than
 * even. The previous value of one half discounted the same fact twice - once
 * in the calibration and again in the curve - and because this term multiplies
 * recruitability, the second discount halved every at-level programme.
 */
export const COMPATIBILITY_AT_LEVEL = 0.80;

/**
 * How quickly compatibility falls away BELOW the programme's level, in
 * percentile points.
 *
 * HEURISTIC. Roster places are contested, so a coach with better options takes
 * them: five points below scores 0.43, ten points 0.23, twenty points 0.07.
 * The A7.7.13 surface found this to be the sensitive parameter - the safe
 * region runs 0.07 to 0.09, and at 0.12 a national contender reaches the
 * outreach slice for an athlete who is not close to it.
 */
export const COMPATIBILITY_DECAY = 0.08;

/**
 * How quickly compatibility saturates toward 1 ABOVE the programme's level.
 *
 * HEURISTIC, and held equal to the decay so the curve keeps two parameters
 * rather than three. The direction is the whole point: OVERQUALIFICATION IS
 * NEVER PENALISED HERE. A Division III coach does not turn down a Division I
 * player, so the curve rises and never falls. If a strong athlete does not
 * WANT a weak programme, that is a preference and it belongs in Athlete
 * Opportunity, where competitive-level priority already carries it.
 */
export const COMPATIBILITY_RISE = 0.08;

/**
 * The share of athletic plausibility that survives when no other recruiting
 * evidence favours the athlete.
 *
 * HEURISTIC. A programme with no opening still recruits - squads carry depth,
 * and a coach who rates a player finds a place. phi is how much of that
 * survives: at 0.35 an at-level athlete with no opportunity scores 0.35 of
 * their plausibility rather than nothing.
 */
export const CORE_FLOOR = 0.35;

/**
 * How strongly an already-recruited arrival claims a vacated place.
 *
 * HEURISTIC. Below 1 because an arrival is not a one-for-one replacement: a
 * class is recruited against a squad, not against a specific departure.
 */
export const ARRIVAL_CLAIM_WEIGHT = 0.6;

/**
 * The most of a vacated place that claims may absorb.
 *
 * HEURISTIC. Caps the reduction so that arrivals and returning depth can
 * strongly demote an opening and never delete it - a squad that recruited
 * four midfielders may still take a fifth, and a model that says otherwise is
 * asserting knowledge of a coach's list that we do not have.
 */
export const MAX_CLAIM_SHARE = 0.75;

/** Component weights inside the recruitability core. HEURISTIC. */
export const CORE_WEIGHTS = Object.freeze({
  positionalOpportunity: 0.7,
  internationalPropensity: 0.3,
});

/**
 * Coverage the core must reach before recruitability is scoreable at all.
 *
 * HEURISTIC, and it binds where it matters: for an international athlete it
 * rejects a programme we know only the international history of, because
 * "they sign overseas players" is not an answer to "would they want this one".
 * For a domestic athlete international propensity is NOT_APPLICABLE, so
 * positional opportunity carries the whole core and the floor reduces to
 * requiring it.
 */
export const RECRUITABILITY_COVERAGE_FLOOR = 0.6;

/**
 * A7.7.4 — Recruiting Market Match parameters.
 *
 * ALL HEURISTIC AND UNCALIBRATED TO OUTCOMES. There is no labelled
 * coach-response dataset; these were chosen on reliability, stability and
 * semantics, in that order, and every one sits on a measured plateau rather
 * than at a fitted optimum. See docs/matchmaking-v2-academic-and-recruitability.md.
 */

/**
 * Arrivals a programme must have before its own behaviour is claimed at all.
 *
 * Below it the answer is UNKNOWN rather than the division's rate, because
 * reporting a division's behaviour under a programme's name is the same
 * mistake as reporting an absence as a zero.
 */
export const MARKET_MIN_ARRIVALS = 8;

/** Arrivals at the division rate a programme is treated as also having. */
export const MARKET_PSEUDO_COUNT = 10;

/**
 * The distance band that separates a local footprint from a broad one.
 *
 * Measured from the arrivals themselves: the median domestic recruit travels
 * about 225 km, 61% come from within 300 km and 79% from within 800 km, so a
 * 300 km band sits near the middle of the distribution rather than in a tail.
 * Distance is used rather than state lines because a programme 20 miles
 * across a border is near and one 600 miles away in the same state is not.
 */
export const NEAR_BAND_KM = 300;

/**
 * How much of Coach Recruitability's behavioural range each arm carries.
 *
 * Positional evidence leads because it is about THIS athlete's position in
 * THIS entry year, where market match is a standing property of the
 * programme. They must sum to 1: the athletic ceiling is exactly reached when
 * both are 1, which is what keeps plausibility a ceiling rather than a term.
 */
export const BEHAVIOUR_WEIGHTS = Object.freeze({ positional: 0.75, market: 0.25 });

/**
 * -- A7.18: WHAT AN UNMEASURED POSITIONAL NEED IS WORTH ---------------------
 *
 * HEURISTIC, and the most openly invented number in this file. It is the
 * share of positional evidence's range that a programme keeps when we have
 * not measured its opening at all.
 *
 * It exists because A7.13-A7.15 measured what happens without it. Positional
 * evidence entered support linearly, so a programme with no detected opening
 * contributed nothing and its weight was not redistributed: support could not
 * exceed 0.25, Recruitability could not exceed A x 0.5125, and across three
 * athlete profiles NOT ONE of the 220 programmes with a measured zero or an
 * unreadable roster reached the top hundred. The best any of them managed was
 * 129th. That is a structural exclusion of 26% of the eligible universe, and
 * it was produced by an absence of evidence rather than by evidence.
 *
 * The operator's position, recorded at A7.16, is that a detected absence of
 * vacancy is not a coach declining to recruit the position. Transfers,
 * injuries, eligibility changes, position changes and ordinary coach
 * behaviour all move places that no roster snapshot predicts. So a measured
 * zero is mild negative evidence and an unreadable roster is no evidence.
 */
export const POSITIONAL_PRIOR = 0.45;

/**
 * What a MEASURED zero costs against that prior.
 *
 * HEURISTIC. 0.35 of the prior, so a detected absence of opening is worth
 * less than not knowing - which is the whole point of measuring - without
 * falling to the zero that caused the exclusion. See A7.16 for the tournament
 * that rejected a plain floor on exactly this ordering.
 */
export const POSITIONAL_ZERO_PENALTY = 0.35;

/**
 * How a positional result becomes its share of Recruitability's behavioural
 * range. The ordering it enforces, and which A7.16 condition E made
 * load-bearing:
 *
 *   measured zero  <  unknown  <  any positive measurement
 *
 *   unknown        prior                      0.45
 *   measured 0     prior x (1 - penalty)      0.2925
 *   measured p>0   prior + (1 - prior) x p    (0.45, 1]
 *
 * THIS IS NOT RENORMALISATION. The A7.7.3 failure was that an unknown
 * signal's weight was absorbed by the surviving signal, so a programme we
 * knew less about could outrank one we had measured. Here the unknown takes a
 * prior IN ITS OWN SLOT and can never exceed a positive measurement, because
 * `prior + (1 - prior) * p > prior` for every p > 0.
 *
 * @param {number|null} value  the measured positional opportunity, or null when unknown
 */
export function positionalSupport(value, {
  prior = POSITIONAL_PRIOR, zeroPenalty = POSITIONAL_ZERO_PENALTY,
} = {}) {
  if (value === null || value === undefined) return prior;
  if (value <= 0) return prior * (1 - zeroPenalty);
  return prior + ((1 - prior) * value);
}
