import fs from 'node:fs';
import path from 'node:path';
import db from '../db/client.js';

/**
 * The gate that stands between a generated directory and Cloudflare.
 *
 * THE INVARIANT THIS EXISTS TO PROTECT. Once a profile URL has been sent to a
 * coach it must keep resolving for as long as the athlete is being
 * represented. Nothing else we do — a Render deploy, a failed generation,
 * publishing a different athlete, an outage — may take it away. Only a
 * deliberate archive may.
 *
 * WHY IT IS NEEDED. A Pages deployment is a snapshot of a directory, so every
 * publish reships the whole site. That is the right model: it means one
 * athlete's page cannot go stale while another's is fresh. But it also means
 * ANY athlete missing from the candidate directory is deleted from the public
 * site by the next publish of anybody else. And an athlete goes missing very
 * easily: `exportAll` skips anyone failing the required core, so an operator
 * clearing a contact email in the morning and publishing a different athlete
 * in the afternoon silently withdraws the first athlete's page. The coach is
 * then shown the neutral "no longer shared" notice — indistinguishable from
 * the athlete having withdrawn from representation. Nothing logs an error and
 * nothing looks wrong on our side.
 *
 * WHY IDENTITY, NOT COUNTING. A page-count comparison would miss the case that
 * matters most: publishing a new athlete while an existing one drops out keeps
 * the count identical. So the check is a set difference over stable slugs —
 * every athlete whose URL may already be in an inbox must be present in the
 * candidate by name, and a page nobody expects is refused too.
 *
 * The bias is deliberate and one-directional: refusing a questionable publish
 * costs an operator a few minutes, breaking a link in a coach's inbox costs an
 * athlete a recruiting cycle.
 */

/** Slugs are generated by lib/tokens.js; anything else in p/ is not ours. */
const SLUG_FILE = /^([A-Za-z0-9]{1,32})\.html$/;

/** Hosts a coach's browser cannot reach, in any endpoint we might have baked in. */
const UNREACHABLE_HOST = /(?:https?:)?\/\/(?:localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])/i;

/**
 * Every athlete whose public URL is — or may already be — in a coach's inbox.
 *
 * Two ways in, because `published_at` alone is not enough. It is stamped on
 * the athlete whose button was pressed, but a publish ships everyone, so an
 * athlete can be live on Cloudflare with a null `published_at`. A live
 * outreach token is the stronger signal: it means a link was minted for a
 * named coach. The union is what must survive.
 *
 * Archived athletes are excluded, and that exclusion is the ONLY sanctioned
 * way for a page to leave the site.
 */
export function expectedPublicAthletes(database = db) {
  return database.prepare(`
    SELECT p.id, p.full_name, p.public_slug AS slug, p.published_at
    FROM players p
    WHERE p.archived_at IS NULL
      AND p.public_slug IS NOT NULL
      AND (
        p.published_at IS NOT NULL
        OR EXISTS (
          SELECT 1 FROM outreach o
          WHERE o.athlete_id = p.id AND o.revoked_at IS NULL
        )
      )
    ORDER BY p.full_name
  `).all();
}

/** Slug → athlete, for deciding whether a file in the candidate belongs there. */
export function slugOwners(database = db) {
  const rows = database.prepare(
    'SELECT id, full_name, public_slug AS slug, archived_at FROM players WHERE public_slug IS NOT NULL'
  ).all();
  const byslug = new Map();
  const duplicates = [];
  for (const row of rows) {
    if (byslug.has(row.slug)) duplicates.push(row.slug);
    else byslug.set(row.slug, row);
  }
  return { byslug, duplicates };
}

/** Where the record of the last successful deployment lives. */
export function ledgerPath(outputDir) {
  return `${outputDir}.deployed.json`;
}

/**
 * What the last successful deployment actually contained.
 *
 * Kept beside the site rather than inside it, so it is never itself published,
 * and on the persistent disk so it survives a Render restart. Its absence is
 * not an error — the database-derived expectation is the primary check and
 * stands alone. The ledger only adds the case the database cannot see: a slug
 * that was demonstrably shipped, is now gone, and was never archived.
 */
export function readLedger(outputDir) {
  try {
    const raw = fs.readFileSync(ledgerPath(outputDir), 'utf-8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed?.slugs) ? parsed : null;
  } catch {
    return null;
  }
}

export function writeLedger(outputDir, { slugs, deploymentUrl = null, at = new Date().toISOString() }) {
  const body = { at, deploymentUrl, slugs: [...slugs].sort() };
  fs.writeFileSync(ledgerPath(outputDir), `${JSON.stringify(body, null, 2)}\n`);
  return body;
}

/**
 * Decides whether a generated directory is safe to make public.
 *
 * Returns every failure rather than the first, because the operator is going
 * to have to fix them and one round trip per problem is a bad way to spend an
 * afternoon.
 */
export function validateCandidate({
  dir,
  endpoint,
  skipped = [],
  ledger = null,
  database = db,
} = {}) {
  const failures = [];
  const expected = expectedPublicAthletes(database);
  const { byslug, duplicates } = slugOwners(database);
  const missingReason = new Map(skipped.map((s) => [s.id, s.missing]));

  const pagesDir = path.join(dir, 'p');
  const present = new Map();

  if (!fs.existsSync(pagesDir)) {
    failures.push('the candidate has no p/ directory — nothing was generated.');
  } else {
    for (const name of fs.readdirSync(pagesDir)) {
      const match = SLUG_FILE.exec(name);
      if (!match) {
        failures.push(`p/${name} is not a profile page. Only <slug>.html belongs in the candidate.`);
        continue;
      }
      const file = path.join(pagesDir, name);
      const size = fs.statSync(file).size;
      if (size === 0) {
        failures.push(`p/${name} is zero bytes. A coach opening it would get a blank page.`);
        continue;
      }
      present.set(match[1], { file, size });
    }
  }

  // 1. Nobody who is already out there may be absent. This is the check the
  //    whole module exists for.
  for (const athlete of expected) {
    if (present.has(athlete.slug)) continue;
    const why = missingReason.get(athlete.id);
    failures.push(
      why?.length
        ? `${athlete.full_name} is already public but is missing from the candidate, because their `
          + `record now lacks ${why.join(', ')}. Publishing would take their link down for every coach `
          + `already holding it. Restore the missing field, or archive them deliberately.`
        : `${athlete.full_name} is already public but has no page in the candidate. Publishing would `
          + `take their link down for every coach already holding it.`
    );
  }

  // 2. A page nobody can account for is either a stale file from a previous
  //    run or an archived athlete leaking back onto the site.
  for (const slug of present.keys()) {
    const owner = byslug.get(slug);
    if (!owner) {
      failures.push(`p/${slug}.html belongs to no athlete in the database — a stale file from an earlier build.`);
    } else if (owner.archived_at) {
      failures.push(`p/${slug}.html is ${owner.full_name}, who is archived. Their page must not be republished.`);
    }
  }

  // 3. Slug stability. Two athletes on one slug means one of them serves the
  //    other's profile, which is worse than a dead link.
  for (const slug of duplicates) {
    failures.push(`public slug "${slug}" is held by more than one athlete.`);
  }

  // 4. Nothing may ship pointing at a machine no coach can reach. A page whose
  //    tracker posts to localhost renders perfectly and reports nothing, and
  //    the loss is only discovered after the coach has been and gone.
  for (const [slug, { file }] of present) {
    const html = fs.readFileSync(file, 'utf-8');
    if (UNREACHABLE_HOST.test(html)) {
      failures.push(`p/${slug}.html contains a localhost URL. It would render but record nothing.`);
    }
    if (endpoint && !html.includes(endpoint)) {
      failures.push(`p/${slug}.html does not carry the expected tracking endpoint (${endpoint}).`);
    }
  }

  // 5. The collector and the exclusion notice are part of the site, not extras.
  //    Without the worker every page is an ungated static file, which serves
  //    revoked links and records nothing.
  for (const required of ['_worker.js', 'robots.txt']) {
    const file = path.join(dir, required);
    if (!fs.existsSync(file)) failures.push(`${required} is missing from the candidate.`);
    else if (fs.statSync(file).size === 0) failures.push(`${required} is zero bytes.`);
  }

  // 6. Anything the last deployment demonstrably served, that is not archived,
  //    must still be here. Catches the athlete the database no longer counts
  //    as expected but who is nonetheless live.
  if (ledger) {
    for (const slug of ledger.slugs) {
      if (present.has(slug)) continue;
      const owner = byslug.get(slug);
      if (owner?.archived_at) continue; // the sanctioned way out
      failures.push(
        `${owner?.full_name || `slug ${slug}`} was in the last deployment and is not in this one, `
        + 'and has not been archived. A deployment may only lose a page through a deliberate archive.'
      );
    }
  }

  // 7. Never replace a populated site with an empty one.
  if (present.size === 0) {
    failures.push('the candidate contains no profile pages at all.');
  }

  return { ok: failures.length === 0, failures, slugs: [...present.keys()], expected };
}
