/**
 * Roster-file spellings that name a school the registry spells differently.
 *
 * The roster sources write a school's full official name; the men's registry
 * writes a terse one ("Avila University" against "Avila", "Xavier University of
 * Louisiana" against "Xavier (LA)"). Every join in the product is
 * `roster_players.college_name = colleges.name`, so a school spelled two ways is
 * a school the product cannot see: 79 NAIA men's programmes held four seasons of
 * roster data that no feature could read, 2,512 of those rows from 2026 alone.
 *
 * This is a TABLE, not a matcher, on purpose. The candidates were generated by
 * resolving identity words against the registry, scoped hard by sport AND
 * division and refusing anything ambiguous, then every row was checked against
 * the registry entry's own city and state. Shipping the rule instead of the
 * result would re-run those heuristics on data they were never checked against,
 * and this matcher has already corrupted three columns doing exactly that -- see
 * the note at the top of schoolMatch.js. A wrong line here is one line to delete.
 *
 * Division is what makes the dangerous cases safe. Georgetown College (NAIA,
 * Kentucky) and Georgetown University (D1) share every identity word, as do
 * University of Providence (NAIA, Montana) and Providence (D1), and St. Thomas
 * University (NAIA, Florida) and St. Thomas (D1, Minnesota). Resolving on name
 * alone maps all three onto a flagship programme.
 *
 * Two entries are renames rather than spellings: Union College (KY) became Union
 * Commonwealth University in 2024, and the Penn State branch campuses are
 * written out in full by their roster source.
 */

const ALIASES = {
  "mens-soccer|NAIA": {
    "Aquinas College (Michigan)": "Aquinas",
    "Arizona Christian University": "Arizona Christian",
    "Avila University": "Avila",
    "Baker University": "Baker",
    "Benedictine College": "Benedictine (KS)",
    "Bethany College (Kansas)": "Bethany (KS)",
    "Bethel University (IN)": "Bethel (IN)",
    "Bethel University (TN)": "Bethel (TN)",
    "Bryan College": "Bryan",
    "Carroll College": "Carroll (MT)",
    "Central Christian College of Kansas": "Central Christian",
    "Central Methodist University": "Central Methodist",
    "Clarke University": "Clarke",
    "Columbia College (MO)": "Columbia (MO)",
    "Cornerstone University": "Cornerstone",
    "Dakota Wesleyan University": "Dakota Wesleyan",
    "Doane University": "Doane",
    "Dordt University": "Dordt",
    "Eastern Oregon University": "Eastern Oregon",
    "Evangel University": "Evangel",
    "Florida Memorial University": "Florida Memorial",
    "Freed-Hardeman University": "Freed-Hardeman",
    "Friends University": "Friends",
    "Georgetown College": "Georgetown (KY)",
    "Goshen College": "Goshen",
    "Grace College": "Grace",
    "Grand View University": "Grand View",
    "Hannibal-LaGrange University": "Hannibal-LaGrange",
    "Hastings College": "Hastings",
    "Huntington University": "Huntington",
    "Indiana Wesleyan University": "Indiana Wesleyan",
    "John Brown University": "John Brown",
    "Kansas Wesleyan University": "Kansas Wesleyan",
    "Kentucky Christian University": "Kentucky Christian",
    "Life University": "Life (GA)",
    "Lindsey Wilson University": "Lindsey Wilson",
    "MidAmerica Nazarene University": "MidAmerica Nazarene",
    "Midland University": "Midland",
    "Midway University": "Midway",
    "Missouri Baptist University": "Missouri Baptist",
    "Morningside University": "Morningside",
    "Mount Mercy University": "Mount Mercy",
    "Mount Vernon Nazarene University": "Mount Vernon Nazarene",
    "Northwestern College (Iowa)": "Northwestern (IA)",
    "Olivet Nazarene University": "Olivet Nazarene",
    "Ottawa University": "Ottawa",
    "Park University": "Park",
    "Point University": "Point (GA)",
    "Rocky Mountain College": "Rocky Mountain",
    "Saint Ambrose University": "Saint Ambrose",
    "Southeastern University (Florida)": "Southeastern University",
    "Southern Oregon University": "Southern Oregon",
    "Southwestern College (Kansas)": "Southwestern (KS)",
    "Spring Arbor University": "Spring Arbor",
    "St. Thomas University (Florida)": "Saint Thomas (FL)",
    "Sterling College (Kansas)": "Sterling",
    "Tabor College": "Tabor",
    "Taylor University": "Taylor",
    "Trinity Christian College": "Trinity Christian",
    "Union Commonwealth University": "Union (KY)",
    "University of Pikeville": "Pikeville",
    "University of Providence": "Providence (MT)",
    "University of Saint Mary": "Saint Mary (KS)",
    "University of Science and Arts of Oklahoma": "Science & Arts (OK)",
    "University of St. Francis (IL)": "Saint Francis (IL)",
    "University of the Cumberlands": "Cumberlands",
    "University of the Southwest": "University of the Southwest (New Mexico)",
    "Waldorf University": "Waldorf",
    "Warner University": "Warner",
    "Wayland Baptist University": "Wayland Baptist",
    "Webber International University": "Webber International",
    "William Penn University": "William Penn",
    "William Woods University": "William Woods",
    "Xavier University of Louisiana": "Xavier (LA)",
  },
  "womens-soccer|NCAA D3": {
    "Pennsylvania State University-Penn State Brandywine": "Penn State Brandywine",
  },
};

/**
 * The registry's spelling of a school, or the name unchanged.
 *
 * Scoped by sport and division because the same words name different
 * institutions across them.
 */
export function registrySchoolName(name, { sport, division } = {}) {
  const table = ALIASES[`${sport}|${division}`];
  return (table && table[String(name || '').trim()]) || name;
}

/** Exposed for the test that asserts every target exists in the registry. */
export const ROSTER_SCHOOL_ALIASES = ALIASES;
